ProjetoLI3: interface.h File Reference
interface.h File Reference
#include "date.h"
#include "pair.h"
#include "list.h"
#include "user.h"
#include "gmodule.h"
#include "myuser.h"
#include "mypost.h"
#include "mytree.h"
#include "mydate.h"
#include "myheap.h"
#include "loading.h"
#include "mytags.h"
#include "stdlib.h"
#include "string.h"
Typedefs
typedef struct TCD_community * TAD_community
Functions
TAD_community init ()
Função inicializa a estrutura da comunidade.
TAD_community load (TAD_community com, char *dump_path)
Função dá load aos ficheiros xml.
STR_pair info_from_post (TAD_community com, long id)
Função retorna a informacao de um post.
LONG_list top_most_active (TAD_community com, int N)
Função que calcula os N utilizadores com mais posts.
LONG_pair total_posts (TAD_community com, Date begin, Date end)
Função que dado um intervalo de tempo obtem o numero total de perguntas e respostas.
LONG_list questions_with_tag (TAD_community com, char *tag, Date begin, Date end)
Função que dado um intervalo de tempo retornar todas as perguntas contendo uma determinada tag.
USER get_user_info (TAD_community com, long id)
Função que dado um id de um user devolve informacao sobre este mesmo.
LONG_list most_voted_answers (TAD_community com, int N, Date begin, Date end)
Função que dado um intervalo de tempo calcula os N posts com melhor score.
LONG_list most_answered_questions (TAD_community com, int N, Date begin, Date end)
Função que dado um intervalo de tempo calcula as N perguntas com mais respostas.
LONG_list contains_word (TAD_community com, char *word, int N)
Função que obtém os id's das N perguntas mais recentes cujo título contém uma dada palavra.
LONG_list both_participated (TAD_community com, long id1, long id2, int N)
Função que dado 2 users retorna as N perguntas em que ambos participaram.
long better_answer (TAD_community com, long id)
Função que dado um id de um post devolve a resposta melhor cotada desse post.
LONG_list most_used_best_rep (TAD_community com, int N, Date begin, Date end)
Função que obtém o número de ocorrencias das N tags mais usadas num dado período de tempo pelos N users com maior reputação.
TAD_community clean (TAD_community com)
Função que liberta a memória da estrutura.
Typedef Documentation
typedef struct TCD_community* TAD_community
Definition at line 17 of file interface.h.
Function Documentation
long better_answer (TAD_community com, long id)
Função que dado um id de um post devolve a resposta melhor cotada desse post.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
id Id do post
Returns
ID da respota com melhor pontuacao,retorna -2 caso nao haja nenhuma respota, -3 caso a pergunta nao seja encontrado o post e -4 caso o id do post dado nao corresponda a uma pergunta.
Definition at line 716 of file interface.c.
References freeMYUSER(), freepost(), get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getCommentsP(), getFilhosP(), getIdP(), getOwnerIdP(), getPostTypeIdP(), getREPMYUSER(), getScoreP(), TCD_community::posts_Id, search_POSTID(), search_USER(), and TCD_community::users.
{
     STACKPOST arr = NULL;
     MYUSER men;
     int scoreatual, scoremax;
     scoremax = scoreatual = 0;
     int n, i,result = -2;
     MYPOST pergunta = search_POSTID(com->posts_Id,id);
     MYPOST resposta = NULL;
     if (!pergunta){
       freepost(pergunta);
       return -3;
     }
     if(getPostTypeIdP(pergunta) != 1){
       freepost(pergunta);
       return -4;
     }
     arr = getFilhosP(pergunta);
     if(arr == NULL){
       freepost(pergunta);
       return -2;
     }
     n = get_NUM_eleSTACKPOST(arr);
     for(i = 0; i < n; i++){
       resposta = get_ele_index_STACKPOST(arr, i);
       men = search_USER(com->users, getOwnerIdP(resposta));
       scoreatual =(getScoreP(resposta) * 0.65 + getREPMYUSER(men) * 0.25  + getCommentsP(resposta) * 0.1);
       freeMYUSER(men);
       if (scoreatual > scoremax){
         scoremax = scoreatual;
         result = getIdP(resposta);
       }
     }
     freepost(pergunta);
     return result;
 }
LONG_list both_participated (TAD_community com, long id1, long id2, int N)
Função que dado 2 users retorna as N perguntas em que ambos participaram.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
id1 ID do user 1.
id2 ID do user 2.
N Número máximo de N
Returns
LONG_list com as N perguntas mais recentes em que ambos os users participaram, caso a lista seja menor que N os restantes indices ficam com o valor de -2.
Definition at line 652 of file interface.c.
References create_list(), freeMYUSER(), freeSTACKPOST_SEM_CLONE(), get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getIdP(), getMYLISTuser(), hash_long_equals(), initSTACKPOST(), ordenaPOST_MYUSER(), order_STACKPOST(), preenche_hash_table(), preenche_stackpost(), search_USER(), set_list(), and TCD_community::users.
{
   MYUSER user1 = search_USER(com->users,id1);
   MYUSER user2 = search_USER(com->users,id2);
   STACKPOST lista1 = getMYLISTuser(user1);// são clones
   STACKPOST lista2 = getMYLISTuser(user2);// são clones
   int size1, size2, size_f,i;
   size1 = get_NUM_eleSTACKPOST(lista1);
   size2 = get_NUM_eleSTACKPOST(lista2);
   if ((!user1) || (!user2) || size1 == 0 || size2 == 0 || N == 0){
     freeMYUSER(user1);
     freeMYUSER(user2);
     return NULL;
   }
   GHashTable * table = g_hash_table_new_full(&g_int_hash,&hash_long_equals,&free,&free);
   LONG_list l = create_list(N);
   STACKPOST l_aux = size1 < size2 ? lista1 : lista2;
   STACKPOST l_aux2 = size1 < size2 ? lista2 : lista1;
   size_f = size1 < size2 ? size1 : size2;
   size2 = size1 < size2 ? size2 : size1;
   preenche_hash_table(com,table,l_aux,size_f);
   STACKPOST queue = initSTACKPOST(size_f+1);
   preenche_stackpost(com,table,queue,l_aux2,size2);
   order_STACKPOST(queue,&ordenaPOST_MYUSER);
   MYPOST post;
   for(i = 0; i < get_NUM_eleSTACKPOST(queue) &&  i < N; i++){
     post = get_ele_index_STACKPOST(queue,i);
     set_list(l,i,getIdP(post));
   }
   if (i < N){
     for(; i < N; i++)
       set_list(l,i,-2);
   }
   freeMYUSER(user1);
   freeMYUSER(user2);
   g_hash_table_destroy(table);
   freeSTACKPOST_SEM_CLONE(queue);
   return l;
 }
TAD_community clean (TAD_community com)
Função que liberta a memória da estrutura.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
Returns
Apontador para a estrutura apos levar free.
Definition at line 930 of file interface.c.
References freeHASH_TAGS(), freeMYHEAP(), freeSTACK(), freeTREE_AVL(), freeTreeUSER(), TCD_community::num_posts, TCD_community::posts_Date, TCD_community::posts_Id, TCD_community::pre_posts, TCD_community::pre_rep, TCD_community::rep_users, TCD_community::tags, and TCD_community::users.
{
   freeTreeUSER(com->users);
   freeTREE_AVL(com->posts_Id);
   freeTREE_AVL(com->posts_Date);
   freeSTACK(com->pre_posts);
   freeMYHEAP(com->num_posts);
   freeSTACK(com->pre_rep);
   freeMYHEAP(com->rep_users);
   freeHASH_TAGS(com->tags);
   return com;
 }
LONG_list contains_word (TAD_community com, char * word, int N)
Função que obtém os id's das N perguntas mais recentes cujo título contém uma dada palavra.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
word Palavra a ser procurada nos títulos.
N Número máximo de resultados N.
Returns
LONG_list com as N perguntas mais recentes que contêm a palavra dada.
Definition at line 541 of file interface.c.
References cmp_longs(), contains_word_arr(), create_list(), freeSTACK(), get_NUM_eleSTACK(), initSTACK(), TCD_community::posts_Date, sort_list(), stack_tolonglist(), trans_stack(), and trans_tree().
{
   STACK arr = initSTACK(1);
   if(N <= 0 || !word)
     return NULL;
   trans_tree(com->posts_Date, &contains_word_arr, arr, word, NULL, NULL, 4, N);
   int n = get_NUM_eleSTACK(arr) - 1;
   LONG_list res = create_list(n + 1);
   trans_stack(arr, &stack_tolonglist, res, &n, NULL);
   if(res)
     sort_list(res, &cmp_longs);
   freeSTACK(arr);
   return res;
 }
USER get_user_info (TAD_community com, long id)
Função que dado um id de um user devolve informacao sobre este mesmo.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
id Id do post.
Returns
Estrutura USER com a biografia e os 10 posts mais recentes desse mesmo user, retorna -2 nos indices dos posts apartir do momento que nao seja encontrado mais posts desse user.
Definition at line 303 of file interface.c.
References create_user(), freeMYUSER(), getBiography(), getNposts(), search_USER(), and TCD_community::users.
{
   MYUSER user = search_USER(com->users,id);
   if(!user)
     return NULL;
   int aux = 0;
   long * posts;
   posts = getNposts(user,10,&aux);
   if(aux != 10){
     for(;aux < 10; aux++)
       posts[aux] = -2;
   }
   char* aux2 = getBiography(user);
   USER info = create_user(aux2,posts);
   freeMYUSER(user);
   free(aux2);
   free(posts);
   return info;
 }
STR_pair info_from_post (TAD_community com, long id)
Função retorna a informacao de um post.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
id Id do post
Returns
STR_pair com o title e name do user, retorna NULL em caso de nao ser encontrado.
Definition at line 119 of file interface.c.
References create_str_pair(), freeMYUSER(), freepost(), getOwnerIdP(), getPIdP(), getPostTypeIdP(), getTitleP(), getUsername(), TCD_community::posts_Id, search_POSTID(), search_USER(), and TCD_community::users.
{
   char * title = NULL;
   char * user = NULL;
   STR_pair result = NULL;
   MYPOST post = search_POSTID(com->posts_Id,id);
   if(!post){
     return result;
   }
   if(getPostTypeIdP(post) == 2){ // resposta
     freepost(post);
     post = search_POSTID(com->posts_Id, getPIdP(post)); // se for uma respota vai buscar o seu pai( sua pergunta )
   }
   title = getTitleP(post);
   MYUSER us = search_USER(com->users, getOwnerIdP(post));
   user = getUsername(us);
   result = create_str_pair(title,user);
   freeMYUSER(us);
   freepost(post);
   free(user);
   free(title);
   return result;
 }
TAD_community init ()
Função inicializa a estrutura da comunidade.
Returns
Apontador para a estrutura inicializada.
Definition at line 27 of file interface.c.
                     {
   TAD_community aux = malloc(sizeof(struct TCD_community));
   return aux;
 }
TAD_community load (TAD_community com, char * dump_path)
Função dá load aos ficheiros xml.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
dump_path String com a diretoria onde se encontram os ficheiros.
Returns
Apontador para a estura carregada em memoria.
Definition at line 79 of file interface.c.
References all_nodes_TREE(), createMYPOST_TREES(), createMYTAGS_HASH(), createMYUSERS_TREE(), initHEAP(), MAX_DUMP_PATH_SIZE, NUM_nodes(), TCD_community::num_posts, num_posts_na_HEAP(), num_rep_na_HEAP(), ordenaMYUSER_ALL_NODES(), TCD_community::posts_Date, TCD_community::posts_Id, TCD_community::pre_posts, TCD_community::pre_rep, TCD_community::rep_users, TCD_community::tags, and TCD_community::users.
{
   char path [MAX_DUMP_PATH_SIZE];
   TREE users,postsDate = NULL,posts_ID = NULL;
   sprintf(path,"%s/Users.xml",dump_path);
   users = createMYUSERS_TREE(path);
   sprintf(path,"%s/Posts.xml",dump_path);
   createMYPOST_TREES(path, &posts_ID, &postsDate, users);
   sprintf(path,"%s/Tags.xml",dump_path);
   com->tags = createMYTAGS_HASH(path);
   com->users = users;
   com->posts_Date = postsDate;
   com->posts_Id = posts_ID;
   all_nodes_TREE(com->users,&ordenaMYUSER_ALL_NODES,NULL);
   com->rep_users = initHEAP(NUM_nodes(users));
   com->pre_rep = NULL;
   all_nodes_TREE(users,&num_rep_na_HEAP,com->rep_users);
   com->num_posts = initHEAP(NUM_nodes(users));
   com->pre_posts = NULL;
   all_nodes_TREE(users,&num_posts_na_HEAP,com->num_posts);
   return com;
 }
LONG_list most_answered_questions (TAD_community com, int N, Date begin, Date end)
Função que dado um intervalo de tempo calcula as N perguntas com mais respostas.
Parameters
com Apontador para a base de dados.
N Número de posts a calcular.
begin Data do começo do intervalo.
end Data do fim do intervalo.
Returns
LONG_list com os N utilizadores que mais votaram no intervalo dado, caso nao encontre N utilizadores retornara -2 nos restantes indices do array.
Definition at line 443 of file interface.c.
References create_list(), DatetoMYDATE(), free_MYdate(), freeMYHEAP(), initHEAP(), NUM_nodes(), pop(), postList_to_HEAP_nresp(), TCD_community::posts_Date, TCD_community::posts_Id, set_list(), and trans_tree().
{
   HEAP h = initHEAP(NUM_nodes(com->posts_Id));
   LONG_list l = create_list(N);
   MYDATE b1 = DatetoMYDATE(begin);
   MYDATE e1 = DatetoMYDATE(end);
   trans_tree(com->posts_Date,&postList_to_HEAP_nresp,h,NULL,begin,end,5,0);
   int i;
   long key,data;
   for(i=0; i < N && (get_NUM_eleHEAP(h) > 0); i++){
     pop(h,&key,&data);
     set_list(l,i,data);
   }
   if (i < N){
     for(; i<N ;i++)
       set_list(l,i,-2);
   }
   freeMYHEAP(h);
   free_MYdate(b1);
   free_MYdate(e1);
   return l;
 }
LONG_list most_used_best_rep (TAD_community com, int N, Date begin, Date end)
Função que obtém o número de ocorrencias das N tags mais usadas num dado período de tempo pelos N users com maior reputação.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
N Número máximo de tags.
begin Início do período de tempo.
end Final do período de tempo.
Returns
LONG_list com as N tags mais usados num dado intervalo de tempo pelos users com mais reputacao.
Definition at line 876 of file interface.c.
References create_list(), DatetoMYDATE(), free_MYdate(), freeMYHEAP(), freeMYUSER(), getMYLISTuser(), hash_to_heap(), initHEAP(), most_used_best_rep_node(), n_users_with_more_rep(), pop(), search_USER(), set_list(), trans_arr(), and TCD_community::users.
{
   if(N <= 0 || !begin || !end)
     return NULL;
   GHashTable * ocorrencias = g_hash_table_new_full(&g_direct_hash,&g_direct_equal, NULL,&free);
   MYDATE mybegin = DatetoMYDATE(begin);                   //transformar Date no nosso tipo
   MYDATE myend = DatetoMYDATE(end);                     // de dados MYDATE
   long * users = NULL;
   int i;
   MYUSER user;
   STACKPOST posts;
   users = n_users_with_more_rep(com, N);
   for(i = 0; i < N && users[i] != -2; i++){               //preencher array com N
     user = search_USER(com->users, users[i]);             //users com  maior reputação
     if(user) {
       posts = getMYLISTuser(user);
       trans_arr(posts, &most_used_best_rep_node, com, ocorrencias, mybegin, myend);
       freeMYUSER(user);
     }
   }
   free(users);
   free_MYdate(mybegin);
   free_MYdate(myend);
   int size = g_hash_table_size(ocorrencias);
   HEAP heap = initHEAP((long) size);
   g_hash_table_foreach(ocorrencias, &hash_to_heap, heap);
   if(size > N)
     size = N;
   LONG_list res = create_list(size);
   long id, oc;
   for(i = 0; i < size; i++) {
     pop(heap, &oc, &id);
     set_list(res, i, id);
   }
   freeMYHEAP(heap);
   g_hash_table_destroy(ocorrencias);
   return res;
 }
LONG_list most_voted_answers (TAD_community com, int N, Date begin, Date end)
Função que dado um intervalo de tempo calcula os N posts com melhor score.
Parameters
com Apontador para a base de dados.
N Número de respostas.
begin Data do começo do intervalo.
end Data do fim do intervalo.
Returns
LONG_list com os N utilizadores que mais votaram no dado intervalo de tempo, caso nao encontre N utilizadores retornara -2 nos restantes indices do array.
Definition at line 354 of file interface.c.
References all_nodes_With_Condition(), create_list(), DatetoMYDATE(), free_MYdate(), freeMYHEAP(), initHEAP(), NUM_nodes(), pop(), postList_to_HEAP_score(), TCD_community::posts_Date, TCD_community::posts_Id, and set_list().
{
   HEAP h = initHEAP(NUM_nodes(com->posts_Id));
   LONG_list l = create_list(N);
   MYDATE b1 = DatetoMYDATE(begin);
   MYDATE e1 = DatetoMYDATE(end);
   all_nodes_With_Condition(com->posts_Date,b1,e1,&postList_to_HEAP_score,h,NULL);
   int i;
   long key,data;
   for(i=0; i < N && (get_NUM_eleHEAP(h) > 0); i++){
     pop(h,&key,&data);
     set_list(l,i,data);
   }
   if (i < N){
     for(; i<N ;i++)
       set_list(l,i,-2);
   }
   freeMYHEAP(h);
   free_MYdate(b1);
   free_MYdate(e1);
   return l;
 }
LONG_list questions_with_tag (TAD_community com, char * tag, Date begin, Date end)
Função que dado um intervalo de tempo retornar todas as perguntas contendo uma determinada tag.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
tag Tag.
begin Data inicial da procura.
end Data final da procura.
Returns
LONG_list com o id de todas as tags que ocorreram no dado intervalo de tempo.
Definition at line 272 of file interface.c.
References all_nodes_With_Condition(), create_list(), DatetoMYDATE(), filtraTags(), free_MYdate(), freeSTACK(), get_ELE_index(), get_NUM_eleSTACK(), initSTACK(), TCD_community::posts_Date, and set_list().
{
   MYDATE nbegin,nend;
   nbegin = DatetoMYDATE(begin);
   nend   = DatetoMYDATE(end);
   STACK result = initSTACK(1);
   all_nodes_With_Condition(com->posts_Date,nbegin,nend,&(filtraTags),&result, tag);
   free_MYdate(nbegin);
   free_MYdate(nend);
   LONG_list final= create_list(get_NUM_eleSTACK(result));
   int i=0;
   int c;
   int max = get_NUM_eleSTACK(result);
   for(i=(max-1), c = 0; i >= 0; i--, c++)
     set_list(final,c,(long)get_ELE_index(result,i));
   freeSTACK(result);
   return final;
 }
LONG_list top_most_active (TAD_community com, int N)
Função que calcula os N utilizadores com mais posts.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
N Número de jogadores.
Returns
LONG_list com os N users mais ativos, retorna -2 nos restantes indices da lista caso exceda o numero de users.
Definition at line 161 of file interface.c.
References create_list(), get_ELE_index(), get_NUM_eleHEAP(), get_NUM_eleSTACK(), initSTACK(), insereSTACK(), TCD_community::num_posts, pop(), TCD_community::pre_posts, and set_list().
{
   LONG_list l = create_list(N);
   int i;
   long id,key;
   if (com->pre_posts == NULL)
     com->pre_posts = initSTACK((long)N);
   if (((long) N) <= get_NUM_eleSTACK(com->pre_posts)){
     for(i=0; i < N; i++){
       set_list(l,i,get_ELE_index(com->pre_posts,i));
     }
   }
   else{
     for(i=0;i < get_NUM_eleSTACK(com->pre_posts); i++)
       set_list(l,i,get_ELE_index(com->pre_posts,i));
     for(; i < N && get_NUM_eleHEAP(com->num_posts) > 0; i++){
       pop(com->num_posts,&key,&id);
       com->pre_posts = insereSTACK(com->pre_posts,id);
       set_list(l,i,id);
     }
     if (i < N){
       for(; i < N; i++)
         set_list(l,i,-2);
     }
   }
   return l;
 }
LONG_pair total_posts (TAD_community com, Date begin, Date end)
Função que dado um intervalo de tempo obtem o numero total de perguntas e respostas.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
being Data inicial da procura
end Data final da procura
Returns
LONG_pair com o numero total de perguntas e resposta no dado intervalo.
Definition at line 216 of file interface.c.
References all_nodes_With_Condition(), create_long_pair(), DatetoMYDATE(), filtraPerguntasRespostas(), free_MYdate(), and TCD_community::posts_Date.
{
   long res1, res2 ;
   res1 = res2 = 0;
   MYDATE nbegin,nend;
   nbegin = DatetoMYDATE(begin);
   nend = DatetoMYDATE(end);
   all_nodes_With_Condition(com->posts_Date,nbegin,nend,&(filtraPerguntasRespostas),&res1,&res2);
   free_MYdate(nbegin);
   free_MYdate(nend);
   LONG_pair result = create_long_pair(res1,res2);
   return result;
 }