ProjetoLI3: interface.c File Reference
interface.c File Reference
Ficheiro contendo funções predefinidas para responder as querys bem como as suas funcoes auxiliares.
#include "interface.h"
Classes
struct TCD_community
Macros
#define MAX_DUMP_PATH_SIZE 300
Functions
TAD_community init ()
Função inicializa a estrutura da comunidade.
static void num_posts_na_HEAP (void *data, void *dataaux)
Função auxiliar adiciona a informação da data de um nodo MYUSER numa heap.
static void num_rep_na_HEAP (void *data, void *dataaux)
Função auxiliar que adiciona a informação da data de um nodo MYUSER numa heap para reputação.
static void ordenaMYUSER_ALL_NODES (void *data1, void *data2)
Função auxiliar que ordena os posts de um user.
TAD_community load (TAD_community com, char *dump_path)
Função dá load aos ficheiros xml.
STR_pair info_from_post (TAD_community com, long id)
Função retorna a informacao de um post.
LONG_list top_most_active (TAD_community com, int N)
Função que calcula os N utilizadores com mais posts.
static void filtraPerguntasRespostas (void *data, void *perguntas, void *respostas)
Função auxiliar que corre num nodo e adiciona as perguntas/respostas a contadores.
LONG_pair total_posts (TAD_community com, Date begin, Date end)
Função que dado um intervalo de tempo obtem o numero total de perguntas e respostas.
static void filtraTags (void *data, void *result, void *tag)
Função auxiliar que corre num nodo e verifica a existencia de uma tag.
LONG_list questions_with_tag (TAD_community com, char *tag, Date begin, Date end)
Função que dado um intervalo de tempo retornar todas as perguntas contendo uma determinada tag.
USER get_user_info (TAD_community com, long id)
Função que dado um id de um user devolve informacao sobre este mesmo.
static void postList_to_HEAP_score (void *data, void *dataaux, void *lal)
Função auxiliar que adiciona a informação da data de um nodo STACKPOST numa heap para scores.
LONG_list most_voted_answers (TAD_community com, int N, Date begin, Date end)
Função que dado um intervalo de tempo calcula os N posts com melhor score.
static int how_many_post_interval (STACKPOST st, MYDATE begin, MYDATE end)
Função auxiliar que conta o número de post num intervalo.
static void postList_to_HEAP_nresp (void *data, void *dataaux, void *begin, void *end)
Função auxiliar que adiciona a informação da data de um nodo STACKPOST numa heap para perguntas com mais respostas.
LONG_list most_answered_questions (TAD_community com, int N, Date begin, Date end)
Função que dado um intervalo de tempo calcula as N perguntas com mais respostas.
static int contains_word_node (void *post, void *arr, void *word, void *n, void *nulla)
Função a aplicar aos posts a ser visitados na travessia, auxiliar á query 8.
static void contains_word_arr (void *arr, void *res, void *word, void *n)
Função a aplicar ao array de posts efetuados no mesmo dia, auxiliar á query 8.
static void stack_tolonglist (long num, void *longlist, void *n, void *nulla)
Função auxiliar que passa a key (neste caso do tipo long) de um nodo da nossa estrutura MYLIST para lista de longs dos professores.
LONG_list contains_word (TAD_community com, char *word, int N)
Função que obtém os id's das N perguntas mais recentes cujo título contém uma dada palavra.
static int hash_long_equals (const void *data1, const void *data2)
Função auxiliar que compara duas keys e diz que os seus valores são iguais.
static void preenche_hash_table (TAD_community com, GHashTable *table, STACKPOST l_aux, int size_f)
Função auxiliar que insere posts uma hashtable.
static void preenche_stackpost (TAD_community com, GHashTable *table, STACKPOST queue, STACKPOST l_aux2, int size2)
Função auxiliar que retira posts de uma hashtable para um stackpost.
LONG_list both_participated (TAD_community com, long id1, long id2, int N)
Função que dado 2 users retorna as N perguntas em que ambos participaram.
long better_answer (TAD_community com, long id)
Função que dado um id de um post devolve a resposta melhor cotada desse post.
static long * n_users_with_more_rep (TAD_community com, int N)
Função auxiliar que calcula os N utilizadores com melhor rep.
static int most_used_best_rep_node (void *vpost, void *vcom, void *ocorrencias, void *begin, void *end)
Função auxiliar à query 11 que será aplicada a cada nodo da lista de posts em cada nodo da árvore organizada por datas, durante a travessia.
void hash_to_heap (gpointer key, gpointer value, gpointer data)
Função auxiliar compatível com a API do glib para inserir numa heap os dados da hashtable com as ocorrencias de cada tag.
LONG_list most_used_best_rep (TAD_community com, int N, Date begin, Date end)
Função que obtém o número de ocorrencias das N tags mais usadas num dado período de tempo pelos N users com maior reputação.
TAD_community clean (TAD_community com)
Função que liberta a memória da estrutura.
Detailed Description
Ficheiro contendo funções predefinidas para responder as querys bem como as suas funcoes auxiliares.
Definition in file interface.c.
Macro Definition Documentation
#define MAX_DUMP_PATH_SIZE 300
Definition at line 7 of file interface.c.
Function Documentation
long better_answer (TAD_community com, long id)
Função que dado um id de um post devolve a resposta melhor cotada desse post.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
id Id do post
Returns
ID da respota com melhor pontuacao,retorna -2 caso nao haja nenhuma respota, -3 caso a pergunta nao seja encontrado o post e -4 caso o id do post dado nao corresponda a uma pergunta.
Definition at line 716 of file interface.c.
References freeMYUSER(), freepost(), get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getCommentsP(), getFilhosP(), getIdP(), getOwnerIdP(), getPostTypeIdP(), getREPMYUSER(), getScoreP(), TCD_community::posts_Id, search_POSTID(), search_USER(), and TCD_community::users.
{
     STACKPOST arr = NULL;
     MYUSER men;
     int scoreatual, scoremax;
     scoremax = scoreatual = 0;
     int n, i,result = -2;
     MYPOST pergunta = search_POSTID(com->posts_Id,id);
     MYPOST resposta = NULL;
     if (!pergunta){
       freepost(pergunta);
       return -3;
     }
     if(getPostTypeIdP(pergunta) != 1){
       freepost(pergunta);
       return -4;
     }
     arr = getFilhosP(pergunta);
     if(arr == NULL){
       freepost(pergunta);
       return -2;
     }
     n = get_NUM_eleSTACKPOST(arr);
     for(i = 0; i < n; i++){
       resposta = get_ele_index_STACKPOST(arr, i);
       men = search_USER(com->users, getOwnerIdP(resposta));
       scoreatual =(getScoreP(resposta) * 0.65 + getREPMYUSER(men) * 0.25  + getCommentsP(resposta) * 0.1);
       freeMYUSER(men);
       if (scoreatual > scoremax){
         scoremax = scoreatual;
         result = getIdP(resposta);
       }
     }
     freepost(pergunta);
     return result;
 }
LONG_list both_participated (TAD_community com, long id1, long id2, int N)
Função que dado 2 users retorna as N perguntas em que ambos participaram.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
id1 ID do user 1.
id2 ID do user 2.
N Número máximo de N
Returns
LONG_list com as N perguntas mais recentes em que ambos os users participaram, caso a lista seja menor que N os restantes indices ficam com o valor de -2.
Definition at line 652 of file interface.c.
References create_list(), freeMYUSER(), freeSTACKPOST_SEM_CLONE(), get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getIdP(), getMYLISTuser(), hash_long_equals(), initSTACKPOST(), ordenaPOST_MYUSER(), order_STACKPOST(), preenche_hash_table(), preenche_stackpost(), search_USER(), set_list(), and TCD_community::users.
{
   MYUSER user1 = search_USER(com->users,id1);
   MYUSER user2 = search_USER(com->users,id2);
   STACKPOST lista1 = getMYLISTuser(user1);// são clones
   STACKPOST lista2 = getMYLISTuser(user2);// são clones
   int size1, size2, size_f,i;
   size1 = get_NUM_eleSTACKPOST(lista1);
   size2 = get_NUM_eleSTACKPOST(lista2);
   if ((!user1) || (!user2) || size1 == 0 || size2 == 0 || N == 0){
     freeMYUSER(user1);
     freeMYUSER(user2);
     return NULL;
   }
   GHashTable * table = g_hash_table_new_full(&g_int_hash,&hash_long_equals,&free,&free);
   LONG_list l = create_list(N);
   STACKPOST l_aux = size1 < size2 ? lista1 : lista2;
   STACKPOST l_aux2 = size1 < size2 ? lista2 : lista1;
   size_f = size1 < size2 ? size1 : size2;
   size2 = size1 < size2 ? size2 : size1;
   preenche_hash_table(com,table,l_aux,size_f);
   STACKPOST queue = initSTACKPOST(size_f+1);
   preenche_stackpost(com,table,queue,l_aux2,size2);
   order_STACKPOST(queue,&ordenaPOST_MYUSER);
   MYPOST post;
   for(i = 0; i < get_NUM_eleSTACKPOST(queue) &&  i < N; i++){
     post = get_ele_index_STACKPOST(queue,i);
     set_list(l,i,getIdP(post));
   }
   if (i < N){
     for(; i < N; i++)
       set_list(l,i,-2);
   }
   freeMYUSER(user1);
   freeMYUSER(user2);
   g_hash_table_destroy(table);
   freeSTACKPOST_SEM_CLONE(queue);
   return l;
 }
TAD_community clean (TAD_community com)
Função que liberta a memória da estrutura.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
Returns
Apontador para a estrutura apos levar free.
Definition at line 930 of file interface.c.
References freeHASH_TAGS(), freeMYHEAP(), freeSTACK(), freeTREE_AVL(), freeTreeUSER(), TCD_community::num_posts, TCD_community::posts_Date, TCD_community::posts_Id, TCD_community::pre_posts, TCD_community::pre_rep, TCD_community::rep_users, TCD_community::tags, and TCD_community::users.
{
   freeTreeUSER(com->users);
   freeTREE_AVL(com->posts_Id);
   freeTREE_AVL(com->posts_Date);
   freeSTACK(com->pre_posts);
   freeMYHEAP(com->num_posts);
   freeSTACK(com->pre_rep);
   freeMYHEAP(com->rep_users);
   freeHASH_TAGS(com->tags);
   return com;
 }
LONG_list contains_word (TAD_community com, char * word, int N)
Função que obtém os id's das N perguntas mais recentes cujo título contém uma dada palavra.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
word Palavra a ser procurada nos títulos.
N Número máximo de resultados N.
Returns
LONG_list com as N perguntas mais recentes que contêm a palavra dada.
Definition at line 541 of file interface.c.
References cmp_longs(), contains_word_arr(), create_list(), freeSTACK(), get_NUM_eleSTACK(), initSTACK(), TCD_community::posts_Date, sort_list(), stack_tolonglist(), trans_stack(), and trans_tree().
{
   STACK arr = initSTACK(1);
   if(N <= 0 || !word)
     return NULL;
   trans_tree(com->posts_Date, &contains_word_arr, arr, word, NULL, NULL, 4, N);
   int n = get_NUM_eleSTACK(arr) - 1;
   LONG_list res = create_list(n + 1);
   trans_stack(arr, &stack_tolonglist, res, &n, NULL);
   if(res)
     sort_list(res, &cmp_longs);
   freeSTACK(arr);
   return res;
 }
static void contains_word_arr (void * arr, void * res, void * word, void * n) static
Função a aplicar ao array de posts efetuados no mesmo dia, auxiliar á query 8.
Parameters
arr Array onde estão armazenados os ids de posts efetuados no mesmo dia.
res Array onde estão a ser guardados os ids dos posts de resposta à query.
word Palavra a ser procurada nos títulos.
n Número máximo de resultados N.
Definition at line 511 of file interface.c.
References contains_word_node(), and trans_arr().
{
   if(arr == NULL)
     return;
   trans_arr(arr, &contains_word_node, res, word, n, NULL);
 }
static int contains_word_node (void * post, void * arr, void * word, void * n, void * nulla) static
Função a aplicar aos posts a ser visitados na travessia, auxiliar á query 8.
Parameters
post Post a ser visitado.
arr Array onde serão guardados os id's dos posts relevantes.
word Palavra a ser procurada nos títulos.
n Número máximo de resultados N.
Returns
Inteiro que funciona como boolean.
Definition at line 480 of file interface.c.
References getIdP(), getPostTypeIdP(), getTitleP(), insereSTACK(), and wordstr().
{
   if(post == NULL || *((int *) n) <= 0)
     return 0;
   MYPOST cpost = (MYPOST) post;
                     // se não for uma pergunta
   if(getPostTypeIdP(cpost) != 1)    // então
     return 0;           // retornar
   STACK carr = (STACK) arr;
   char * cword = (char *) word, * title;
   title = getTitleP(cpost);
   if(wordstr(title, cword) ) {  // se o titulo contem a palavra
     insereSTACK(carr, getIdP(cpost));
     int * cn = (int *) n;
     (*cn)--;
   }
   free(title);
   return 1;
 }
static void filtraPerguntasRespostas (void * data, void * perguntas, void * respostas) static
Função auxiliar que corre num nodo e adiciona as perguntas/respostas a contadores.
Parameters
data Apontador para a informação a filtar.
perguntas Número de perguntas.
respostas Número de respostas.
Definition at line 200 of file interface.c.
References getCounter1_STACKPOST(), and getCounter2_STACKPOST().
{
   STACKPOST arr = (STACKPOST) data;
   if (data != NULL){ //p->1 r->2
     *(long *)perguntas += getCounter1_STACKPOST(arr);
     *(long *)respostas += getCounter2_STACKPOST(arr);
   }
 }
static void filtraTags (void * data, void * result, void * tag) static
Função auxiliar que corre num nodo e verifica a existencia de uma tag.
Parameters
data Apontador para a informação a filtar.
result Lista de posts com essa tag.
tag Tag a verificar.
Definition at line 240 of file interface.c.
References existeTag(), get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getIdP(), getPostTypeIdP(), and insereSTACK().
{
   STACK resultado;
   STACKPOST arr = (STACKPOST) data;
   int existe = 0,i;
   MYPOST post;
   if (data != NULL){
     int max = get_NUM_eleSTACKPOST(arr);
     for(i=0; i < max; i++){
       post = get_ele_index_STACKPOST(arr,i);
       if (getPostTypeIdP(post) == 1){
         existe = existeTag(post,tag);
         if (existe){
           resultado =  *(STACK*)result;
           resultado = insereSTACK(resultado, getIdP(post));
           *(STACK*) result = resultado;
         }
       }
     }
   }
 }
USER get_user_info (TAD_community com, long id)
Função que dado um id de um user devolve informacao sobre este mesmo.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
id Id do post.
Returns
Estrutura USER com a biografia e os 10 posts mais recentes desse mesmo user, retorna -2 nos indices dos posts apartir do momento que nao seja encontrado mais posts desse user.
Definition at line 303 of file interface.c.
References create_user(), freeMYUSER(), getBiography(), getNposts(), search_USER(), and TCD_community::users.
{
   MYUSER user = search_USER(com->users,id);
   if(!user)
     return NULL;
   int aux = 0;
   long * posts;
   posts = getNposts(user,10,&aux);
   if(aux != 10){
     for(;aux < 10; aux++)
       posts[aux] = -2;
   }
   char* aux2 = getBiography(user);
   USER info = create_user(aux2,posts);
   freeMYUSER(user);
   free(aux2);
   free(posts);
   return info;
 }
static int hash_long_equals (const void * data1, const void * data2) static
Função auxiliar que compara duas keys e diz que os seus valores são iguais.
Parameters
data1 Apontador para a primeira key.
data2 Apontador para a segunda key.
Returns
Inteiro que funciona como boolean.
Definition at line 568 of file interface.c.
{
   long id1 = *(long *) data1;
   long id2 = *(long *) data2;
   return (id1 == id2);
 }
void hash_to_heap (gpointer key, gpointer value, gpointer data)
Função auxiliar compatível com a API do glib para inserir numa heap os dados da hashtable com as ocorrencias de cada tag.
Parameters
key Chave da entrada atual, ou seja, o id da tag.
value Valor a entrada atual, ou seja, o número de ocorrencias da tag.
data Apontador para a heap para a qual queremos passar a informação.
Definition at line 859 of file interface.c.
References insereHEAP().
{
   HEAP heap = (HEAP) data;
   long ocorrencias, id;
   ocorrencias = (long) *((int *) value);
   id = *((long *) key);
   insereHEAP(heap, ocorrencias, id);
 }
static int how_many_post_interval (STACKPOST st, MYDATE begin, MYDATE end) static
Função auxiliar que conta o número de post num intervalo.
Parameters
st Apontador para a stack de posts.
begin Apontador para o inicio do intervalo.
end Apontador para o fim do intervalo.
Returns
Numero de posts num dado intervalo.
Definition at line 389 of file interface.c.
References compare_MYDATE_AVL(), free_MYdate(), get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getDateP(), and getPostTypeIdP().
{
   long i, tam = get_NUM_eleSTACKPOST(st);
   int count = 0,r1,r2;
   MYDATE pdate;
   MYPOST post;
   if (st){
     for(i=0; i < tam; i++){
       post = get_ele_index_STACKPOST(st,i);
       pdate = getDateP(post);
       if (getPostTypeIdP(post) == 2){
         r1 = compare_MYDATE_AVL(begin,pdate);
         r2 = compare_MYDATE_AVL(end,pdate);
         if (r1 >= 0 && r2 <= 0)
           count++;
       }
       free_MYdate(pdate);
     }
   }
   return count;
 }
STR_pair info_from_post (TAD_community com, long id)
Função retorna a informacao de um post.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
id Id do post
Returns
STR_pair com o title e name do user, retorna NULL em caso de nao ser encontrado.
Definition at line 119 of file interface.c.
References create_str_pair(), freeMYUSER(), freepost(), getOwnerIdP(), getPIdP(), getPostTypeIdP(), getTitleP(), getUsername(), TCD_community::posts_Id, search_POSTID(), search_USER(), and TCD_community::users.
{
   char * title = NULL;
   char * user = NULL;
   STR_pair result = NULL;
   MYPOST post = search_POSTID(com->posts_Id,id);
   if(!post){
     return result;
   }
   if(getPostTypeIdP(post) == 2){ // resposta
     freepost(post);
     post = search_POSTID(com->posts_Id, getPIdP(post)); // se for uma respota vai buscar o seu pai( sua pergunta )
   }
   title = getTitleP(post);
   MYUSER us = search_USER(com->users, getOwnerIdP(post));
   user = getUsername(us);
   result = create_str_pair(title,user);
   freeMYUSER(us);
   freepost(post);
   free(user);
   free(title);
   return result;
 }
TAD_community init ()
Função inicializa a estrutura da comunidade.
Returns
Apontador para a estrutura inicializada.
Definition at line 27 of file interface.c.
                     {
   TAD_community aux = malloc(sizeof(struct TCD_community));
   return aux;
 }
TAD_community load (TAD_community com, char * dump_path)
Função dá load aos ficheiros xml.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
dump_path String com a diretoria onde se encontram os ficheiros.
Returns
Apontador para a estura carregada em memoria.
Definition at line 79 of file interface.c.
References all_nodes_TREE(), createMYPOST_TREES(), createMYTAGS_HASH(), createMYUSERS_TREE(), initHEAP(), MAX_DUMP_PATH_SIZE, NUM_nodes(), TCD_community::num_posts, num_posts_na_HEAP(), num_rep_na_HEAP(), ordenaMYUSER_ALL_NODES(), TCD_community::posts_Date, TCD_community::posts_Id, TCD_community::pre_posts, TCD_community::pre_rep, TCD_community::rep_users, TCD_community::tags, and TCD_community::users.
{
   char path [MAX_DUMP_PATH_SIZE];
   TREE users,postsDate = NULL,posts_ID = NULL;
   sprintf(path,"%s/Users.xml",dump_path);
   users = createMYUSERS_TREE(path);
   sprintf(path,"%s/Posts.xml",dump_path);
   createMYPOST_TREES(path, &posts_ID, &postsDate, users);
   sprintf(path,"%s/Tags.xml",dump_path);
   com->tags = createMYTAGS_HASH(path);
   com->users = users;
   com->posts_Date = postsDate;
   com->posts_Id = posts_ID;
   all_nodes_TREE(com->users,&ordenaMYUSER_ALL_NODES,NULL);
   com->rep_users = initHEAP(NUM_nodes(users));
   com->pre_rep = NULL;
   all_nodes_TREE(users,&num_rep_na_HEAP,com->rep_users);
   com->num_posts = initHEAP(NUM_nodes(users));
   com->pre_posts = NULL;
   all_nodes_TREE(users,&num_posts_na_HEAP,com->num_posts);
   return com;
 }
LONG_list most_answered_questions (TAD_community com, int N, Date begin, Date end)
Função que dado um intervalo de tempo calcula as N perguntas com mais respostas.
Parameters
com Apontador para a base de dados.
N Número de posts a calcular.
begin Data do começo do intervalo.
end Data do fim do intervalo.
Returns
LONG_list com os N utilizadores que mais votaram no intervalo dado, caso nao encontre N utilizadores retornara -2 nos restantes indices do array.
Definition at line 443 of file interface.c.
References create_list(), DatetoMYDATE(), free_MYdate(), freeMYHEAP(), initHEAP(), NUM_nodes(), pop(), postList_to_HEAP_nresp(), TCD_community::posts_Date, TCD_community::posts_Id, set_list(), and trans_tree().
{
   HEAP h = initHEAP(NUM_nodes(com->posts_Id));
   LONG_list l = create_list(N);
   MYDATE b1 = DatetoMYDATE(begin);
   MYDATE e1 = DatetoMYDATE(end);
   trans_tree(com->posts_Date,&postList_to_HEAP_nresp,h,NULL,begin,end,5,0);
   int i;
   long key,data;
   for(i=0; i < N && (get_NUM_eleHEAP(h) > 0); i++){
     pop(h,&key,&data);
     set_list(l,i,data);
   }
   if (i < N){
     for(; i<N ;i++)
       set_list(l,i,-2);
   }
   freeMYHEAP(h);
   free_MYdate(b1);
   free_MYdate(e1);
   return l;
 }
LONG_list most_used_best_rep (TAD_community com, int N, Date begin, Date end)
Função que obtém o número de ocorrencias das N tags mais usadas num dado período de tempo pelos N users com maior reputação.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
N Número máximo de tags.
begin Início do período de tempo.
end Final do período de tempo.
Returns
LONG_list com as N tags mais usados num dado intervalo de tempo pelos users com mais reputacao.
Definition at line 876 of file interface.c.
References create_list(), DatetoMYDATE(), free_MYdate(), freeMYHEAP(), freeMYUSER(), getMYLISTuser(), hash_to_heap(), initHEAP(), most_used_best_rep_node(), n_users_with_more_rep(), pop(), search_USER(), set_list(), trans_arr(), and TCD_community::users.
{
   if(N <= 0 || !begin || !end)
     return NULL;
   GHashTable * ocorrencias = g_hash_table_new_full(&g_direct_hash,&g_direct_equal, NULL,&free);
   MYDATE mybegin = DatetoMYDATE(begin);                   //transformar Date no nosso tipo
   MYDATE myend = DatetoMYDATE(end);                     // de dados MYDATE
   long * users = NULL;
   int i;
   MYUSER user;
   STACKPOST posts;
   users = n_users_with_more_rep(com, N);
   for(i = 0; i < N && users[i] != -2; i++){               //preencher array com N
     user = search_USER(com->users, users[i]);             //users com  maior reputação
     if(user) {
       posts = getMYLISTuser(user);
       trans_arr(posts, &most_used_best_rep_node, com, ocorrencias, mybegin, myend);
       freeMYUSER(user);
     }
   }
   free(users);
   free_MYdate(mybegin);
   free_MYdate(myend);
   int size = g_hash_table_size(ocorrencias);
   HEAP heap = initHEAP((long) size);
   g_hash_table_foreach(ocorrencias, &hash_to_heap, heap);
   if(size > N)
     size = N;
   LONG_list res = create_list(size);
   long id, oc;
   for(i = 0; i < size; i++) {
     pop(heap, &oc, &id);
     set_list(res, i, id);
   }
   freeMYHEAP(heap);
   g_hash_table_destroy(ocorrencias);
   return res;
 }
static int most_used_best_rep_node (void * vpost, void * vcom, void * ocorrencias, void * begin, void * end) static
Função auxiliar à query 11 que será aplicada a cada nodo da lista de posts em cada nodo da árvore organizada por datas, durante a travessia.
Parameters
vpost Nodo atual.
vcom Apontador para a comunidade (para podermos aceder à hash table das tags)
ocorrencias Hash table criada para registar as ocorrencias de cada tag.
begin Data de início do período de tempo da query11.
end Data de fim do período de tempo da query11.
Returns
Inteiro usado como boolean.
Definition at line 809 of file interface.c.
References compare_MYDATE_AVL(), free_MYdate(), free_StringArray(), getDateP(), getPostTypeIdP(), getTagsP(), and TCD_community::tags.
{
   if(vpost == NULL)
     return 0;
   MYPOST post = (MYPOST) vpost;
   int i;
   if(getPostTypeIdP(post) != 1)
     return 0;
   MYDATE date = getDateP(post);
   int r1 = compare_MYDATE_AVL((MYDATE) begin,  date);
   int r2 = compare_MYDATE_AVL((MYDATE) end, date);
   free_MYdate(date);
   if(r1 < 0 || r2 > 0)
     return 0;
   char ** tags = NULL;
   tags = getTagsP(post);
   long * keyid;
   int * oc;
   TAD_community com = (TAD_community) vcom;
   if(!tags)
     return 0;
   for(i = 0; tags[i]; i++)
     if((keyid = g_hash_table_lookup(com->tags, tags[i])) != NULL){
       if((oc = g_hash_table_lookup(ocorrencias, keyid)) != NULL){
         (*oc)++;
       }
       else {
         oc = malloc(sizeof(int));
         (*oc) = 1;
         g_hash_table_insert(ocorrencias, keyid, oc);
       }
     }
   free_StringArray(tags);
   return 1;
 }
LONG_list most_voted_answers (TAD_community com, int N, Date begin, Date end)
Função que dado um intervalo de tempo calcula os N posts com melhor score.
Parameters
com Apontador para a base de dados.
N Número de respostas.
begin Data do começo do intervalo.
end Data do fim do intervalo.
Returns
LONG_list com os N utilizadores que mais votaram no dado intervalo de tempo, caso nao encontre N utilizadores retornara -2 nos restantes indices do array.
Definition at line 354 of file interface.c.
References all_nodes_With_Condition(), create_list(), DatetoMYDATE(), free_MYdate(), freeMYHEAP(), initHEAP(), NUM_nodes(), pop(), postList_to_HEAP_score(), TCD_community::posts_Date, TCD_community::posts_Id, and set_list().
{
   HEAP h = initHEAP(NUM_nodes(com->posts_Id));
   LONG_list l = create_list(N);
   MYDATE b1 = DatetoMYDATE(begin);
   MYDATE e1 = DatetoMYDATE(end);
   all_nodes_With_Condition(com->posts_Date,b1,e1,&postList_to_HEAP_score,h,NULL);
   int i;
   long key,data;
   for(i=0; i < N && (get_NUM_eleHEAP(h) > 0); i++){
     pop(h,&key,&data);
     set_list(l,i,data);
   }
   if (i < N){
     for(; i<N ;i++)
       set_list(l,i,-2);
   }
   freeMYHEAP(h);
   free_MYdate(b1);
   free_MYdate(e1);
   return l;
 }
static long* n_users_with_more_rep (TAD_community com, int N) static
Função auxiliar que calcula os N utilizadores com melhor rep.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
N Número de utilizadores.
Returns
O array com os N users com mais rep, caso nao sejam encontrado N users retorna -2 no primeiro indice apos nao serem encontrados mais.
Definition at line 771 of file interface.c.
References get_ELE_index(), get_NUM_eleHEAP(), get_NUM_eleSTACK(), initSTACK(), insereSTACK(), pop(), TCD_community::pre_rep, and TCD_community::rep_users.
{
   int i;
   long * array = malloc(N*sizeof(long));
   long id,key;
   if (com->pre_rep == NULL)
     com->pre_rep = initSTACK((long)N);
   if (((long) N) <= get_NUM_eleSTACK(com->pre_rep)){
     for(i=0; i < N; i++){
       array[i] = get_ELE_index(com->pre_rep,i);
     }
   }
   else{
     for(i=0; i < get_NUM_eleSTACK(com->pre_rep); i++)
       array[i] = get_ELE_index(com->pre_rep,i);
     for(; i < N && (get_NUM_eleHEAP(com->rep_users) > 0); i++){
       pop(com->rep_users,&key,&id);
       com->pre_rep = insereSTACK(com->pre_rep,id);
       array[i] = get_ELE_index(com->pre_rep,i);
     }
     if(i < N)
       array[i] = -2;
   }
   return array;
 }
static void num_posts_na_HEAP (void * data, void * dataaux) static
Função auxiliar adiciona a informação da data de um nodo MYUSER numa heap.
Parameters
data Apontador para a data do nodo.
dataaux Apontador para a heap.
Definition at line 40 of file interface.c.
References getCounter1_STACKPOST(), getCounter2_STACKPOST(), getIdMYUSER(), getMYLISTuser(), and insereHEAP().
{
   HEAP h = (HEAP) dataaux;
   MYUSER user = (MYUSER) data;
   STACKPOST st = getMYLISTuser(user);
   long n_post = getCounter1_STACKPOST(st) + getCounter2_STACKPOST(st);
   insereHEAP(h,n_post,getIdMYUSER(user));
 }
static void num_rep_na_HEAP (void * data, void * dataaux) static
Função auxiliar que adiciona a informação da data de um nodo MYUSER numa heap para reputação.
Parameters
data Apontador para a data do nodo.
dataaux Apontador para a heap.
Definition at line 54 of file interface.c.
References getIdMYUSER(), getREPMYUSER(), and insereHEAP().
{
   HEAP h = (HEAP) dataaux;
   MYUSER user = (MYUSER) data;
   insereHEAP(h,getREPMYUSER(user),getIdMYUSER(user));
 }
static void ordenaMYUSER_ALL_NODES (void * data1, void * data2) static
Função auxiliar que ordena os posts de um user.
Parameters
data1 Apontador para o user.
Definition at line 65 of file interface.c.
References getMYLISTuser(), ordenaPOST_MYUSER(), and order_STACKPOST().
{
   MYUSER use = (MYUSER) data1;
   if (use){
     order_STACKPOST(getMYLISTuser(use),&ordenaPOST_MYUSER);
   }
 }
static void postList_to_HEAP_nresp (void * data, void * dataaux, void * begin, void * end) static
Função auxiliar que adiciona a informação da data de um nodo STACKPOST numa heap para perguntas com mais respostas.
Parameters
data Apontador para a data do nodo.
dataaux Apontador para a heap.
begin Apontador para a inicio do intervalo.
fim Apontador para o fim do intervalo.
Definition at line 419 of file interface.c.
References get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getFilhosP(), getIdP(), getPostTypeIdP(), how_many_post_interval(), and insereHEAP().
{
   HEAP h = (HEAP) dataaux;
   STACKPOST arr = (STACKPOST) data;
   MYPOST post = NULL;
   int i;
   long tam = get_NUM_eleSTACKPOST(arr);
   for(i=0; i < tam; i++){
     post = get_ele_index_STACKPOST(arr,i);
     if (post)
       if (getPostTypeIdP(post) == 1)
         insereHEAP(h, how_many_post_interval(getFilhosP(post),(MYDATE) begin,(MYDATE) end), getIdP(post));
         //insereHEAP(h,getAnswersP(post),getIdP(post));
   }
 }
static void postList_to_HEAP_score (void * data, void * dataaux, void * lal) static
Função auxiliar que adiciona a informação da data de um nodo STACKPOST numa heap para scores.
Parameters
data Apontador para a data do nodo.
dataaux Apontador para a heap.
Definition at line 331 of file interface.c.
References get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getIdP(), getPostTypeIdP(), getScoreP(), and insereHEAP().
{
   HEAP h = (HEAP) dataaux;
   STACKPOST arr = (STACKPOST) data;
   MYPOST post = NULL;
   int i;
   long tam = get_NUM_eleSTACKPOST(arr);
   for(i=0; i < tam; i++){
     post = get_ele_index_STACKPOST(arr,i);
     if (post)
       if (getPostTypeIdP(post) == 2)
         insereHEAP(h, getScoreP(post), getIdP(post));
   }
 }
static void preenche_hash_table (TAD_community com, GHashTable * table, STACKPOST l_aux, int size_f) static
Função auxiliar que insere posts uma hashtable.
Parameters
com Apontador para estrutura da comunidade.
table Apontador para a hashtable.
l_aux Lista de posts.
size_f Tamanho máximo da lista.
Definition at line 581 of file interface.c.
References clone_MYPOST_NODEEP(), freepost(), get_ele_index_STACKPOST(), getIdP(), getPIdP(), getPostTypeIdP(), TCD_community::posts_Id, and search_POSTID().
{
   MYPOST novo,novo2,post;
   long * id;
   int i;
   for(i = 0; i < size_f; i++){          //criar a hash_table com o posts do user com menos posts.
     post = get_ele_index_STACKPOST(l_aux,i);
     if (getPostTypeIdP(post) == 1){
       novo = clone_MYPOST_NODEEP(post);
       id = malloc(sizeof(long));
       *id = getIdP(post);
       g_hash_table_insert(table,id,novo);
     }
     else if (getPostTypeIdP(post) == 2){
       novo2 = search_POSTID(com->posts_Id,getPIdP(post)); // procura o pai
       if (novo2){
         novo = clone_MYPOST_NODEEP(novo2); //cria clone simples do pai
         freepost(novo2);// free clone complexo
         id = malloc(sizeof(long));
         *id = getIdP(novo);
         g_hash_table_insert(table,id,novo); // insere
       }
     }
   }
 }
static void preenche_stackpost (TAD_community com, GHashTable * table, STACKPOST queue, STACKPOST l_aux2, int size2) static
Função auxiliar que retira posts de uma hashtable para um stackpost.
Parameters
com Apontador para estrutura da comunidade.
table Apontador para a hashtable.
queue Array para guardar os posts.
l_aux2 Lista de comparação.
size_f Tamanho máximo da lista.
Definition at line 616 of file interface.c.
References freepost(), get_ele_index_STACKPOST(), getIdP(), getPIdP(), getPostTypeIdP(), insere_sem_rep_STACKPOST(), TCD_community::posts_Id, and search_POSTID().
{
   MYPOST post,novo;
   int i;
   long idaux;
   for(i = 0; i < size2; i++){
     post = get_ele_index_STACKPOST(l_aux2,i);
     if (getPostTypeIdP(post) == 1){
       idaux = getIdP(post);
       novo = (MYPOST) g_hash_table_lookup(table,&idaux);
       if (novo){
         insere_sem_rep_STACKPOST(queue,novo);
       }
     }
     else if (getPostTypeIdP(post) == 2){
       novo = search_POSTID(com->posts_Id,getPIdP(post));
       if (novo){
           idaux = getIdP(novo);
           freepost(novo);
           novo = g_hash_table_lookup(table,&idaux);
           if (novo){
             insere_sem_rep_STACKPOST(queue,novo);
           }
         }
       }
   }
 }
LONG_list questions_with_tag (TAD_community com, char * tag, Date begin, Date end)
Função que dado um intervalo de tempo retornar todas as perguntas contendo uma determinada tag.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
tag Tag.
begin Data inicial da procura.
end Data final da procura.
Returns
LONG_list com o id de todas as tags que ocorreram no dado intervalo de tempo.
Definition at line 272 of file interface.c.
References all_nodes_With_Condition(), create_list(), DatetoMYDATE(), filtraTags(), free_MYdate(), freeSTACK(), get_ELE_index(), get_NUM_eleSTACK(), initSTACK(), TCD_community::posts_Date, and set_list().
{
   MYDATE nbegin,nend;
   nbegin = DatetoMYDATE(begin);
   nend   = DatetoMYDATE(end);
   STACK result = initSTACK(1);
   all_nodes_With_Condition(com->posts_Date,nbegin,nend,&(filtraTags),&result, tag);
   free_MYdate(nbegin);
   free_MYdate(nend);
   LONG_list final= create_list(get_NUM_eleSTACK(result));
   int i=0;
   int c;
   int max = get_NUM_eleSTACK(result);
   for(i=(max-1), c = 0; i >= 0; i--, c++)
     set_list(final,c,(long)get_ELE_index(result,i));
   freeSTACK(result);
   return final;
 }
static void stack_tolonglist (long num, void * longlist, void * n, void * nulla) static
Função auxiliar que passa a key (neste caso do tipo long) de um nodo da nossa estrutura MYLIST para lista de longs dos professores.
Parameters
num LList cuja key será passadas.
longlist LONG_list onde serão guardadas as keys.
n Índice onde será inserida a key.
Definition at line 525 of file interface.c.
References set_list().
{
   LONG_list clonglist = (LONG_list) longlist;
   int * cn = (int *) n;
   set_list(clonglist, *cn, num);
   (*cn)--;
 }
LONG_list top_most_active (TAD_community com, int N)
Função que calcula os N utilizadores com mais posts.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
N Número de jogadores.
Returns
LONG_list com os N users mais ativos, retorna -2 nos restantes indices da lista caso exceda o numero de users.
Definition at line 161 of file interface.c.
References create_list(), get_ELE_index(), get_NUM_eleHEAP(), get_NUM_eleSTACK(), initSTACK(), insereSTACK(), TCD_community::num_posts, pop(), TCD_community::pre_posts, and set_list().
{
   LONG_list l = create_list(N);
   int i;
   long id,key;
   if (com->pre_posts == NULL)
     com->pre_posts = initSTACK((long)N);
   if (((long) N) <= get_NUM_eleSTACK(com->pre_posts)){
     for(i=0; i < N; i++){
       set_list(l,i,get_ELE_index(com->pre_posts,i));
     }
   }
   else{
     for(i=0;i < get_NUM_eleSTACK(com->pre_posts); i++)
       set_list(l,i,get_ELE_index(com->pre_posts,i));
     for(; i < N && get_NUM_eleHEAP(com->num_posts) > 0; i++){
       pop(com->num_posts,&key,&id);
       com->pre_posts = insereSTACK(com->pre_posts,id);
       set_list(l,i,id);
     }
     if (i < N){
       for(; i < N; i++)
         set_list(l,i,-2);
     }
   }
   return l;
 }
LONG_pair total_posts (TAD_community com, Date begin, Date end)
Função que dado um intervalo de tempo obtem o numero total de perguntas e respostas.
Parameters
com Estrutura comunidade que guarda as outras estruturas.
being Data inicial da procura
end Data final da procura
Returns
LONG_pair com o numero total de perguntas e resposta no dado intervalo.
Definition at line 216 of file interface.c.
References all_nodes_With_Condition(), create_long_pair(), DatetoMYDATE(), filtraPerguntasRespostas(), free_MYdate(), and TCD_community::posts_Date.
{
   long res1, res2 ;
   res1 = res2 = 0;
   MYDATE nbegin,nend;
   nbegin = DatetoMYDATE(begin);
   nend = DatetoMYDATE(end);
   all_nodes_With_Condition(com->posts_Date,nbegin,nend,&(filtraPerguntasRespostas),&res1,&res2);
   free_MYdate(nbegin);
   free_MYdate(nend);
   LONG_pair result = create_long_pair(res1,res2);
   return result;
 }