ProjetoLI3: loading.h File Reference
loading.h File Reference
#include <mypost.h>
#include <myuser.h>
#include <mydate.h>
#include <glib.h>
#include "/usr/include/libxml2/libxml/parser.h"
#include "/usr/include/libxml2/libxml/xmlwriter.h"
#include "/usr/include/libxml2/libxml/tree.h"
#include "/usr/include/libxml2/libxml/xmlmemory.h"
Functions
int xml_file_to_struct (xmlDocPtr *doc, xmlNodePtr *ptr, char *filepath)
Função que (recorrendo à biblioteca libxml2) efetua o parsing de um ficheiro xml.
int createMYPOST_TREES (char *path, TREE *tree_id, TREE *tree_date, TREE treeusers)
Função que cria as àrvores balanceadas de posts segundo id e data de criação.
Function Documentation
int createMYPOST_TREES (char * path, TREE * tree_id, TREE * tree_date, TREE treeusers)
Função que cria as àrvores balanceadas de posts segundo id e data de criação.
Parameters
path O ficheiro Posts.xml.
tree_id O apontador onde ficará apontada a àrvore ordenada segundo id's.
tree_date O apontador onde ficará apontada a àrvore ordenada segundo datas de criação.
treeusers A árvore de users.
Returns
Inteiro usado como boolean.
Definition at line 60 of file loading.c.
References compare_MYDATE_AVL(), compare_user(), concat_post(), createpost(), createTREE(), free_MYdate(), freeKey(), freepost(), freeSTACKPOST_SEM_CLONE(), getDateP(), getIdP(), getOwnerIdP(), initSTACKPOST(), insere_tree(), insereSTACKPOST(), llist::list, setPostToUSER(), xml_file_to_struct(), and xmltoMYPOST().
{
   xmlDocPtr   doc;
   xmlNodePtr  cur = NULL;
   if( !xml_file_to_struct(&doc, &cur, path)) {              //Load para a estrutura do libxml2 a partir do ficheiro.
     fprintf(stderr, "Could not create user tree from %s\n", path);
     return -1;
   }
   STACKPOST list;
   MYPOST  post;
   long *  keyid;
   TREE  treeid    = createTREE(&compare_user, &freeKey, &freepost,NULL);
   TREE  treedate  = createTREE(&compare_MYDATE_AVL, &free_MYdate, &freeSTACKPOST_SEM_CLONE,&concat_post); //é preciso dar free á data xD pensar como fazer isso.
   for(cur = cur->children; cur; cur = cur->next) {            // Percorre os posts todos.
     if(strcmp("row", (char *) cur->name) == 0) {
       post = createpost(1);                     //Cria um nodo post.
       xmltoMYPOST(post, cur, doc, treeid, treeusers);         //Preenche essa struct post.
       keyid   = malloc(sizeof(long));
       *keyid = getIdP(post);
       setPostToUSER(treeusers, getOwnerIdP(post), post);
       list = initSTACKPOST(1);
       insereSTACKPOST(list,post);
       insere_tree(treeid, keyid, post);               //Insere este nodo na árvore ordenada por id's.
       insere_tree(treedate, getDateP(post), list);              //Insere este nodo na árvore ordenada cronológicamente.
     }
   }
   *tree_id  = treeid;
   *tree_date  = treedate;
   xmlFreeDoc(doc);
   xmlFreeNode(cur);
   xmlCleanupParser();
   return 1;
 }
int xml_file_to_struct (xmlDocPtr * doc, xmlNodePtr * ptr, char * filepath)
Função que (recorrendo à biblioteca libxml2) efetua o parsing de um ficheiro xml.
Parameters
doc O apontador do ficheiro xml.
ptr O apontador da estrutura resultante do parsing do ficheiro xml.
filepath O filepath do ficheiro xml a ser lido e carregado.
Returns
Inteiro usado como boolean
Definition at line 16 of file loading.c.
{
   *doc = xmlParseFile(filepath);
   if (!(*doc)) {
     fprintf(stderr, "Document %s not parsed successfully\n", filepath);
     return -1;
   }
   *ptr = xmlDocGetRootElement(*doc);
   if (!(*ptr)) {
     fprintf(stderr, "%s is an empty document\n", filepath);
     return -2;
   }
   return 1;
 }