ProjetoLI3: mydate.c File Reference
mydate.c File Reference
Ficheiro contendo funções relativa ao modulo MYDATE e funções de transformação de MYDATE para date.
#include "mydate.h"
#include <stdio.h>
Classes
struct mydate
Functions
MYDATE createMYDate (int day, int month, int year)
Função inicializa a estrutura de data.
int get_MYday (MYDATE d)
Função que devolve a informação do dia da data.
int get_MYmonth (MYDATE d)
Função que devolve a informação do mês da data.
int get_MYyear (MYDATE d)
Função que devolve a informação do ano da data.
void free_MYdate (MYDATE d)
Função liberta a memória da data.
int MYdate_size ()
Função calcula o tamanho de uma data.
int compare_MYDATE_AVL (void *data1, void *data2)
Função compara duas datas para árvores.
int compare_MYDATE_LIST (void *data1, void *data2)
Função compara duas datas para listas.
Date MYDATEtoDate (MYDATE a)
Função converte um MYDATE para Date.
MYDATE DatetoMYDATE (Date a)
Função converte um Date para MYDATE.
void printMyDate (MYDATE d)
Imprimir uma data.
Detailed Description
Ficheiro contendo funções relativa ao modulo MYDATE e funções de transformação de MYDATE para date.
Definition in file mydate.c.
Function Documentation
int compare_MYDATE_AVL (void * data1, void * data2)
Função compara duas datas para árvores.
Parameters
data1 Apontador para a data 1.
data2 Apontador para a data 2.
Returns
Inteiro usado como boolean.
Definition at line 82 of file mydate.c.
References mydate::day, mydate::month, and mydate::year.
{
     MYDATE a = (MYDATE) data1;
     MYDATE b = (MYDATE) data2;
     if (a->year == b->year && a->month == b->month && a->day==b->day)
         return 0;
     if (a->year == b->year && a->month == b->month && a->day < b->day)
         return 1;
     if (a->year == b->year && a->month == b->month && a->day > b->day)
         return -1;
     if (a->year == b->year && a->month > b->month)
         return -1;
     if (a->year == b->year && a->month < b->month)
         return 1;
     if (a->year > b->year)
         return -1;
     return 1;
 }
int compare_MYDATE_LIST (void * data1, void * data2)
Função compara duas datas para listas.
Parameters
data1 Apontador para a data 1.
data2 Apontador para a data 2.
Returns
Inteiro usado como boolean.
Definition at line 110 of file mydate.c.
References mydate::day, mydate::month, and mydate::year.
{
   MYDATE a = (MYDATE) data1;
   MYDATE b = (MYDATE) data2;
   if (a->year == b->year && a->month == b->month && a->day==b->day)
     return 0;
   if (a->year == b->year && a->month == b->month && a->day < b->day)
     return 0;
   if (a->year == b->year && a->month == b->month && a->day > b->day)
     return 1;
   if (a->year == b->year && a->month > b->month)
     return 1;
   if (a->year == b->year && a->month < b->month)
     return 0;
   if (a->year > b->year)
     return 1;
   return 0;
 }
MYDATE createMYDate (int day, int month, int year)
Função inicializa a estrutura de data.
Parameters
day Variável para o dia.
month Variável para o mês.
year Variável para o ano.
Returns
Apontador para MYDATE criada.
Definition at line 21 of file mydate.c.
References mydate::day, mydate::month, and mydate::year.
{
     MYDATE d = malloc(sizeof(struct mydate));
     d->day = day;
     d->month = month;
     d->year = year;
     return d;
 }
MYDATE DatetoMYDATE (Date a)
Função converte um Date para MYDATE.
Parameters
a Apontador para Date.
Returns
Apontador para MYDATE.
Definition at line 148 of file mydate.c.
References createMYDate(), get_day(), get_month(), and get_year().
{
   MYDATE aux;
   int dia,mes,ano;
   dia = get_day(a);
   mes = get_month(a);
   ano = get_year(a);
   aux = createMYDate(dia,mes,ano);
   return aux;
 }
void free_MYdate (MYDATE d)
Função liberta a memória da data.
Parameters
d Apontador para a data.
Definition at line 63 of file mydate.c.
{
   if(d != NULL)
       free(d);
 }
int get_MYday (MYDATE d)
Função que devolve a informação do dia da data.
Parameters
d Apontador para a data.
Returns
Inteiro com o valor do dia.
Definition at line 34 of file mydate.c.
References mydate::day.
{
     return d->day;
 }
int get_MYmonth (MYDATE d)
Função que devolve a informação do mês da data.
Parameters
d Apontador para a data.
Returns
Inteiro com o valor do mes.
Definition at line 44 of file mydate.c.
References mydate::month.
{
     return d->month; //change to enum? (Acho que sim. Desta forma já garantimos a limitação necessária)
 }
int get_MYyear (MYDATE d)
Função que devolve a informação do ano da data.
Parameters
d Apontador para a data.
Returns
Inteiro com o valor do ano.
Definition at line 54 of file mydate.c.
References mydate::year.
{
     return d->year;
 }
int MYdate_size ()
Função calcula o tamanho de uma data.
Returns
Tamanho da estrutura .
Definition at line 72 of file mydate.c.
                   {
   return sizeof(struct mydate);
 }
Date MYDATEtoDate (MYDATE a)
Função converte um MYDATE para Date.
Parameters
a Apontador para MYDATE.
Returns
Apontador para Date.
Definition at line 137 of file mydate.c.
References createDate(), mydate::day, mydate::month, and mydate::year.
{
   Date aux;
   aux = createDate(a->day,a->month,a->year);
   return aux;
 }
void printMyDate (MYDATE d)
Imprimir uma data.
Parameters
d Apontador para a data.
Definition at line 164 of file mydate.c.
References get_MYday(), get_MYmonth(), and get_MYyear().
{
   printf("(%d-%d-%d)", get_MYday(d), get_MYmonth(d), get_MYyear(d));
 }