ProjetoLI3: myheap.h File Reference
myheap.h File Reference
#include <stdlib.h>
#include <stdio.h>
Typedefs
typedef struct generico GEN
typedef struct heap * HEAP
typedef struct stack * STACK
Functions
void swap (GEN *v, int i, int d)
Função troca 2 elementos no array.
HEAP initHEAP (long size)
Função que inicializa um heap.
void bubble_up (HEAP *main)
Função que coloca o último elemento adicionado na sua posição correta.
void bubble_down (HEAP *main)
Função que realiza as operações necessárias depois de se retirar um elemento.
void insereHEAP (HEAP h, long key, long data)
Função que insere um novo elemento na heap.
void pop (HEAP h, long *key, long *data)
Função que retira um elemento na heap.
long get_NUM_eleHEAP (HEAP a)
Função que calcula o número de elementos na heap.
void freeMYHEAP (HEAP h)
Função dá free à heap.
int teste_heap (HEAP a)
STACK initSTACK (long size)
Função que inicializa uma stack.
void freeSTACK (STACK a)
Função dá free à stack.
STACK insereSTACK (STACK a, long id)
Função insere um elemento na stack.
long get_NUM_eleSTACK (STACK a)
Função que calcula o número de elementos na stack.
long get_ELE_index (STACK a, int index)
Função que devolve o elemento numa dada posição.
void trans_stack (STACK arr, void(*f_box)(long, void *, void *, void *), void *data1, void *data2, void *data3)
Função percorre uma STACK de longs e aplica a cada nodo uma função.
Typedef Documentation
typedef struct generico GEN
Definition at line 7 of file myheap.h.
typedef struct heap* HEAP
Definition at line 8 of file myheap.h.
typedef struct stack* STACK
Definition at line 9 of file myheap.h.
Function Documentation
void bubble_down (HEAP * main)
Função que realiza as operações necessárias depois de se retirar um elemento.
Parameters
main Apontador para a heap.
Definition at line 93 of file myheap.c.
References heap::array, generico::data, generico::key, LCHILD, main(), heap::n_elem, RCHILD, and swap().
{
   HEAP h = * main;
   int fd,fe,i = 0;
   if (h->n_elem > 0){
     h->n_elem--;
     h->array[i].key = h->array[h->n_elem].key;
     h->array[i].data = h->array[h->n_elem].data;
     fd = RCHILD(i);
     fe = LCHILD(i);
     while(i < h->n_elem && fd < h->n_elem && fe < h->n_elem &&
                       ( (h->array[i].key < h->array[fd].key) ||
                         (h->array[i].key < h->array[fe].key) ||
                         (h->array[i].data > h->array[fd].data && h->array[i].key == h->array[fe].key) ||
                         (h->array[i].data > h->array[fe].data && h->array[i].key == h->array[fe].key) )
       ){
       if (fd < h->n_elem && fe < h->n_elem){
         if (h->array[fe].key > h->array[fd].key){
           swap(h->array,i,fe);
           i = fe;
         }
         else if(h->array[fe].key < h->array[fd].key){
           swap(h->array,i,fd);
           i = fd;
         }
         else{
           if (h->array[fd].data < h->array[fe].data && h->array[fe].key == h->array[fd].key){
             swap(h->array,i,fd);
             i = fd;
           }
           else {
             swap(h->array,i,fe);
             i = fe;
           }
         }
       }
       else if (fd < h->n_elem){
         swap(h->array,i,fd);
         i = fd;
       }
       else {
         swap(h->array,i,fe);
         i = fe;
       }
       fd = RCHILD(i);
       fe = LCHILD(i);
     }
   }
   *main = h;
 }
void bubble_up (HEAP * main)
Função que coloca o último elemento adicionado na sua posição correta.
Parameters
main Apontador para a heap.
Definition at line 64 of file myheap.c.
References heap::array, generico::data, generico::key, main(), heap::n_elem, PARENT, and swap().
{
   HEAP h = * main;
   int pai,i;
   if (h->n_elem > 0){
     i = h->n_elem -1;
     pai = PARENT(i);
     while((h->array[i].key>=h->array[pai].key || h->array[i].data<=h->array[pai].data) && i != pai){
       if (h->array[i].key>h->array[pai].key){
         swap(h->array,pai,i);
         i = pai;
         pai = PARENT(i);
       }
       else {
         if (h->array[i].data < h->array[pai].data && h->array[i].key == h->array[pai].key){
           swap(h->array,pai,i);
           i = pai;
           pai = PARENT(i);
         }
         else break;
       }
     }
   }
   *main = h;
 }
void freeMYHEAP (HEAP h)
Função dá free à heap.
Parameters
h Heap.
Definition at line 180 of file myheap.c.
References heap::array.
{
   if (h){
     free(h->array);
     free(h);
   }
 }
void freeSTACK (STACK a)
Função dá free à stack.
Parameters
a Stack.
Definition at line 205 of file myheap.c.
References stack::array.
{
   if(a){
     free(a->array);
     free(a);
   }
 }
long get_ELE_index (STACK a, int index)
Função que devolve o elemento numa dada posição.
Parameters
a Stack.
index Indíce.
Returns
Elemento na posicao dada.
Definition at line 249 of file myheap.c.
References stack::array, and stack::n_elem.
{
   if ((!a) || a->n_elem <= index)
     return -1;
   return a->array[index];
 }
long get_NUM_eleHEAP (HEAP a)
Função que calcula o número de elementos na heap.
Parameters
a HEAP.
Returns
Numero de elementos na heap.
Definition at line 260 of file myheap.c.
References heap::n_elem.
{
   long x;
   return (x = a ? a->n_elem : 0);
 }
long get_NUM_eleSTACK (STACK a)
Função que calcula o número de elementos na stack.
Parameters
a Stack.
Returns
Número de elementos da stack.
Definition at line 236 of file myheap.c.
References stack::n_elem.
{
   if(a){
     return a->n_elem;
   }
   return 0;
 }
HEAP initHEAP (long size)
Função que inicializa um heap.
Parameters
size Tamanho original da heap.
Returns
Apontador para a HEAP.
Definition at line 51 of file myheap.c.
References heap::array, heap::n_elem, and heap::size.
{
   HEAP aux = malloc(sizeof(struct heap));
   aux->size = size;
   aux->n_elem = 0;
   aux->array = malloc(size*sizeof(struct generico));
   return aux;
 }
STACK initSTACK (long size)
Função que inicializa uma stack.
Parameters
size Tamanho da stack a inicializar.
Returns
Apontador para STACK inicializa.
Definition at line 192 of file myheap.c.
References stack::array, stack::n_elem, and stack::size.
{
   STACK aux = malloc(sizeof(struct stack));
   aux->n_elem = 0;
   aux->size = size;
   aux->array = malloc(size*sizeof(long));
   return aux;
 }
void insereHEAP (HEAP h, long key, long data)
Função que insere um novo elemento na heap.
Parameters
h Heap.
key Valor da key a inserir.
data Valor da data a inserir.
Definition at line 150 of file myheap.c.
References heap::array, bubble_up(), generico::data, generico::key, heap::n_elem, and heap::size.
{
   if (h->n_elem >= h->size){
     h->array = realloc(h->array,sizeof(struct generico)*h->size*2);
     h->size *= 2;
   }
   h->array[h->n_elem].key = key;
   h->array[h->n_elem].data = data;
   h->n_elem++;
   bubble_up(&h);
 }
STACK insereSTACK (STACK a, long id)
Função insere um elemento na stack.
Parameters
a Stack.
id Valor a inserir.
Returns
Apontador para a stack apos ser inserido o elemento, returna NULL caso a stack seja nula.
Definition at line 218 of file myheap.c.
References stack::array, stack::n_elem, and stack::size.
{
   if (!a)
     return NULL;
   if (a->size == a->n_elem){
     a->array = realloc(a->array,sizeof(long)*a->size*2);
     a->size *= 2;
   }
   a->array[a->n_elem++] = id;
   return a;
 }
void pop (HEAP h, long * key, long * data)
Função que retira um elemento na heap.
Parameters
h Heap.
key Apontador para o sítio onde a key fica guardada.
data Apontador para o sítio onde a data fica guardada.
Definition at line 168 of file myheap.c.
References heap::array, bubble_down(), generico::data, generico::key, and heap::n_elem.
{
   if (h->n_elem > 0){
     *key =h->array[0].key;
     *data = h->array[0].data;
     bubble_down(&h);
   }
 }
void swap (GEN * v, int i, int d)
Função troca 2 elementos no array.
Parameters
v Array generico.
i Posição do 1 elemento.
d Posição do 2 elemento.
Definition at line 35 of file myheap.c.
References generico::data, and generico::key.
{
   long aux1 = v[i].key;
   long aux2 = v[i].data;
   v[i].key = v[d].key;
   v[i].data = v[d].data;
   v[d].key = aux1;
   v[d].data = aux2;
 }
int teste_heap (HEAP a)
void trans_stack (STACK arr, void(*)(long, void *, void *, void *) f_box, void * data1, void * data2, void * data3)
Função percorre uma STACK de longs e aplica a cada nodo uma função.
Parameters
arr STACK a ser percorrida.
f_box Função a ser aplicada (cujo o primeiro argumento é o nodo a que ela é aplicada).
data1 Segundo argumento da função a ser aplicada.
data2 Terceiro argumento da função a ser aplicada.
data3 Quarto argumento da função a ser aplicada.
Definition at line 274 of file myheap.c.
References stack::array, and stack::n_elem.
{
   if(arr == NULL)
     return;
   for(int i = 0;i < arr->n_elem; i++)
     f_box(arr->array[i],data1, data2, data3);
 }