ProjetoLI3: mypost.h File Reference
mypost.h File Reference
#include "mydate.h"
#include "mytree.h"
#include "/usr/include/libxml2/libxml/parser.h"
#include "/usr/include/libxml2/libxml/xmlwriter.h"
#include "/usr/include/libxml2/libxml/tree.h"
#include "/usr/include/libxml2/libxml/xmlmemory.h"
#include <stdlib.h>
Typedefs
typedef struct mypost * MYPOST
typedef struct stackpost * STACKPOST
Functions
int trans_arr (STACKPOST arr, int(*f_box)(void *, void *, void *, void *, void *), void *data1, void *data2, void *data3, void *data4)
Função percorre um array e aplica a cada nodo uma função.
int ordenaPOST_MYUSER (const void *data1, const void *data2)
Função que calcula o valor da nova ordenação.
void order_STACKPOST (STACKPOST st, void *func)
Função que ordena uma stackpost.
STACKPOST initSTACKPOST (long size)
Função que inicializa um stackpost.
void incCounter2_STACKPOST (STACKPOST st, long i)
Função que adiciona um valor ao counter2.
void incCounter1_STACKPOST (STACKPOST st, long i)
Função que adiciona um valor ao counter1.
long getCounter1_STACKPOST (STACKPOST st)
Função que devolve o counter 1.
long getCounter2_STACKPOST (STACKPOST st)
Função que devolve o counter 2.
void insereSTACKPOST (STACKPOST st, MYPOST post)
Função que insere um elemento numa stackpost.
void insere_sem_rep_STACKPOST (STACKPOST st, MYPOST post)
Função que insere um elemento sem repetidos numa stackpost.
long get_NUM_eleSTACKPOST (STACKPOST st)
Função que calcula o número de elementos de uma stackpost.
MYPOST get_ele_index_STACKPOST (STACKPOST st, long i)
Função que devolve o elemento na posição dada.
void freeSTACKPOST_SEM_CLONE (STACKPOST st)
Função que dá free a uma stackpost.
void freeSTACKPOST_COM_CLONE (STACKPOST st)
Função que dá free a um clone stackpost.
long getIdP (MYPOST post)
Função que obtém o Id de um post.
int getPostTypeIdP (MYPOST post)
Função que obtém o TypeId de um post.
int getTYPECLONEP (MYPOST post)
Função que verifica se um post é clone ou não.
long getOwnerIdP (MYPOST post)
Função que obtém o OwnerId de um post.
MYDATE getDateP (MYPOST post)
Função que obtém a data de criação de um post.
char * getOwnerNameP (MYPOST post)
Função que inicializa a (nossa) representação de um post na memória.
char * getTitleP (MYPOST post)
Função que obtém o título de um post.
char ** getTagsP (MYPOST post)
Função que obtém as tags de um post.
int getAnswersP (MYPOST post)
Função que obtém o numero de respostas de um post.
int getCommentsP (MYPOST post)
Função que obtém o numero de comentarios de um post.
int getFavsP (MYPOST post)
Função que obtém o numero de favoritos de um post.
long getPIdP (MYPOST post)
Função que obtém o ParentId de um post.
int getScoreP (MYPOST post)
Função que obtém o score de um post.
STACKPOST getFilhosP (MYPOST post)
Função que obtém os filhos de um post.
void setFilhosNoPost (MYPOST post, MYPOST data)
Função mete um post nos filhos desse mesmo post.
MYPOST createpost (int type)
Função que inicializa a (nossa) representação de um post na memória.
void freepost (MYPOST post)
Função que liberta a memória alocada para um dado post.
void free_StringArray (char **arr)
Função que liberta um array de strings.
MYPOST clone_MYPOST_NODEEP (MYPOST post)
Função que produz o clone de um post sem profundidade.
STACKPOST clone_STACKPOST (STACKPOST st)
Função que clona uma STACKPOST.
MYPOST clone_MYPOST_DEEP (MYPOST post)
Função que produz o clone de um post com profundidade.
MYPOST search_POSTID (TREE tree, long id)
Função que procura um post pelo id na estrutura com clone.
void print_posts_MYPOST (MYPOST post)
Função que imprime os ids das respostas a um post.
int existeTag (MYPOST post, char *tag)
Função que verifica se existe uma data tag num post.
void xmltoMYPOST (MYPOST post, xmlNodePtr xml, xmlDocPtr doc, TREE treeid, TREE treeusers)
Função que copia informação de um nodo da estrutura do libxml2 para o análogo da nossa estrutura.
MYDATE xmlToMYDATE (char *value)
Função que processa a string correspondente ao valor Creation date e a transforma numa struct mydate.
char ** xmlToStringArray (char *value)
Função que processa a string correspondente ao valor Tags a transforma num array de strings.
STACKPOST search_POSTDATA (TREE tree, MYDATE data)
Typedef Documentation
typedef struct mypost* MYPOST
Definition at line 15 of file mypost.h.
typedef struct stackpost* STACKPOST
Definition at line 17 of file mypost.h.
Function Documentation
MYPOST clone_MYPOST_DEEP (MYPOST post)
Função que produz o clone de um post com profundidade.
Parameters
post Apontador para o post.
Returns
Apontador para a estrutura clonada.
Definition at line 701 of file mypost.c.
References clone_MYPOST_NODEEP(), clone_STACKPOST(), and mypost::filhos.
{
   MYPOST novo = clone_MYPOST_NODEEP(post);
   novo->filhos = clone_STACKPOST(post->filhos);
   return novo;
 }
MYPOST clone_MYPOST_NODEEP (MYPOST post)
Função que produz o clone de um post sem profundidade.
Parameters
post Apontador para o post.
Returns
Apontador para a estrutura clonada.
Definition at line 656 of file mypost.c.
References mypost::anscount, mypost::cdate, mypost::commcount, createpost(), mypost::favcount, mypost::id, mypost::ownerid, mypost::ownername, mypost::parent_id, mypost::score, mypost::tags, mypost::title, and mypost::typeid.
{
   MYPOST novo = createpost(0);
   novo->id = post->id;
   novo->typeid = post->typeid;
   novo->parent_id = post->parent_id;
   novo->cdate = post->cdate;
   novo->score = post->score;
   novo->ownerid = post->ownerid;
   novo->ownername = post->ownername;
   novo->title = post->title;
   novo->tags = post->tags;
   novo->anscount = post->anscount;
   novo->commcount = post->commcount;
   novo->favcount = post->favcount;
   return novo;
 }
STACKPOST clone_STACKPOST (STACKPOST st)
Função que clona uma STACKPOST.
Parameters
st Apontador para a stackpost.
Returns
Apontador para a estrutura clonada.
Definition at line 679 of file mypost.c.
References stackpost::array, clone_MYPOST_NODEEP(), stackpost::counter1, stackpost::counter2, initSTACKPOST(), stackpost::n_elem, and stackpost::size.
{
   STACKPOST novo = initSTACKPOST(st->n_elem);
   novo->counter1 = st->counter1;
   novo->counter2 = st->counter2;
   novo->n_elem = st->n_elem;
   novo->size = st->n_elem;
   long i;
   MYPOST aux;
   for(i = 0; i < st->n_elem; i++){
     aux = clone_MYPOST_NODEEP(st->array[i]);
     novo->array[i] = aux;
   }
   return novo;
 }
MYPOST createpost (int type)
Função que inicializa a (nossa) representação de um post na memória.
Parameters
type Identicador se o post vai ser ou nao clone. /////VERIFICAR
Returns
Apontador para a struct do post.
Definition at line 584 of file mypost.c.
References mypost::anscount, mypost::cdate, mypost::favcount, mypost::filhos, initSTACKPOST(), mypost::ownerid, mypost::ownername, mypost::parent_id, mypost::tags, mypost::title, and mypost::type.
{
   MYPOST post = malloc(sizeof(struct mypost));
   post->ownername = NULL;
   post->tags  = NULL;
   post->cdate = NULL;
   post->title = NULL;
   post->ownerid = -2;
   post->parent_id = -2;
   post->favcount  = 0;
   post->anscount  = 0;
   post->type = type;
   if (type)
     post->filhos = initSTACKPOST(1);
   else post->filhos = NULL;
   return post;
 }
int existeTag (MYPOST post, char * tag)
Função que verifica se existe uma data tag num post.
Parameters
post Apontador para a struct do post.
tag Tag a verificar.
Returns
Inteiro a ser usado como boolean.
Definition at line 769 of file mypost.c.
References mypost::tags.
{
   int i;
   if(!post->tags)
     return 0;
   for(i=0;post->tags[i] != NULL;i++){
     if(strcmp(post->tags[i],tag) == 0 )
       return 1;
     }
   return 0;
 }
void free_StringArray (char ** arr)
Função que liberta um array de strings.
Parameters
arr O array de strings.
Definition at line 638 of file mypost.c.
{
   if(arr == NULL)
     return;
   int i;
   for(i = 0; arr[i]; i++)
     free(arr[i]);
   free(arr);
 }
void freepost (MYPOST post)
Função que liberta a memória alocada para um dado post.
Parameters
post Apontador para a struct do post.
Definition at line 609 of file mypost.c.
References mypost::cdate, mypost::filhos, free_MYdate(), free_StringArray(), freeSTACKPOST_COM_CLONE(), freeSTACKPOST_SEM_CLONE(), mypost::ownername, mypost::tags, mypost::title, and mypost::type.
{
   if(post == NULL)
     return;
   if (post->type == 1){
     if(post->title != NULL)
       free(post->title);
     if(post->ownername != NULL)
       free(post->ownername);
     free_StringArray(post->tags);
     free_MYdate(post->cdate);
     freeSTACKPOST_SEM_CLONE(post->filhos);
   }
   else {
     freeSTACKPOST_COM_CLONE(post->filhos);
   }
   free(post);
 }
void freeSTACKPOST_COM_CLONE (STACKPOST st)
Função que dá free a um clone stackpost.
Parameters
st STACKPOST.
Definition at line 274 of file mypost.c.
References stackpost::array, freepost(), and stackpost::n_elem.
{
   if (st){
     long i;
     for(i=0; i < st->n_elem; i++)
       freepost(st->array[i]);
     free(st->array);
     free(st);
   }
 }
void freeSTACKPOST_SEM_CLONE (STACKPOST st)
Função que dá free a uma stackpost.
Parameters
st STACKPOST.
Definition at line 263 of file mypost.c.
References stackpost::array.
{
   if (st){
     free(st->array);
     free(st);
   }
 }
MYPOST get_ele_index_STACKPOST (STACKPOST st, long i)
Função que devolve o elemento na posição dada.
Parameters
st STACKPOST.
i Indice a consultar.
Returns
Conteudo do indice i da STACKPOST.
Definition at line 253 of file mypost.c.
References stackpost::array, and stackpost::n_elem.
{
   if (i >= st->n_elem)
     return NULL;
   return st->array[i];
 }
long get_NUM_eleSTACKPOST (STACKPOST st)
Função que calcula o número de elementos de uma stackpost.
Parameters
st STACKPOST.
Returns
Numero de elementos da STACKPOST.
Definition at line 243 of file mypost.c.
References stackpost::n_elem.
{
   return st ? st->n_elem : 0;
 }
int getAnswersP (MYPOST post)
Função que obtém o numero de respostas de um post.
Parameters
post Apontador para a struct do post.
Returns
Numero de respostas do post dado.
Definition at line 472 of file mypost.c.
References mypost::anscount.
{
   return post ? post->anscount : 0;
 }
int getCommentsP (MYPOST post)
Função que obtém o numero de comentarios de um post.
Parameters
post Apontador para a struct do post.
Returns
Numero de comentarios do post dado.
Definition at line 490 of file mypost.c.
References mypost::commcount.
{
     return post ? post->commcount : 0;
 }
long getCounter1_STACKPOST (STACKPOST st)
Função que devolve o counter 1.
Parameters
st STACKPOST.
Returns
Counter 1 da STACKPOST.
Definition at line 170 of file mypost.c.
References stackpost::counter1.
{
   return (st) ? st->counter1 : 0;
 }
long getCounter2_STACKPOST (STACKPOST st)
Função que devolve o counter 2.
Parameters
st STACKPOST.
Returns
Counter 2 da STACKPOST.
Definition at line 179 of file mypost.c.
References stackpost::counter2.
{
   return (st) ? st->counter2 : 0;
 }
MYDATE getDateP (MYPOST post)
Função que obtém a data de criação de um post.
Parameters
post Apontador para a struct do post.
Returns
MYDATE do post dado.
Definition at line 352 of file mypost.c.
References mypost::cdate, createMYDate(), get_MYday(), get_MYmonth(), and get_MYyear().
{
   if(post){
     MYDATE date;
     date = createMYDate(get_MYday(post->cdate),
               get_MYmonth(post->cdate),
               get_MYyear(post->cdate));
       return date;
   }
   return NULL;
 }
int getFavsP (MYPOST post)
Função que obtém o numero de favoritos de um post.
Parameters
post Apontador para a struct do post.
Returns
Numero de favoritos do post dado.
Definition at line 508 of file mypost.c.
References mypost::favcount.
{
     return post ? post->favcount : 0;
 }
STACKPOST getFilhosP (MYPOST post)
Função que obtém os filhos de um post.
Parameters
post Apontador para a struct do post.
Returns
STACKPOST dos filhos do post dado.
Definition at line 563 of file mypost.c.
References mypost::filhos.
{
     return post ? post->filhos : NULL;
 }
long getIdP (MYPOST post)
Função que obtém o Id de um post.
Parameters
post Apontador para a struct do post.
Returns
ID do post dado.
Definition at line 290 of file mypost.c.
References mypost::id.
{
     return post ? post->id : -2;
 }
long getOwnerIdP (MYPOST post)
Função que obtém o OwnerId de um post.
Parameters
post Apontador para a struct do post.
Returns
OwnerID do post dado.
Definition at line 334 of file mypost.c.
References mypost::ownerid.
{
     return post ? post->ownerid : -2;
 }
char* getOwnerNameP (MYPOST post)
Função que inicializa a (nossa) representação de um post na memória.
Parameters
post Apontador para a struct do post.
Returns
OwnerName do post dado.
Definition at line 385 of file mypost.c.
References mystrdup(), and mypost::ownername.
{
     return post ? mystrdup(post->ownername) : NULL;
 }
long getPIdP (MYPOST post)
Função que obtém o ParentId de um post.
Parameters
post Apontador para a struct do post.
Returns
ParentId do post dado.
Definition at line 526 of file mypost.c.
References mypost::parent_id.
{
       return post ? post->parent_id : -2;
 }
int getPostTypeIdP (MYPOST post)
Função que obtém o TypeId de um post.
Parameters
post Apontador para a struct do post.
Returns
PostType do post dado.
Definition at line 308 of file mypost.c.
References mypost::typeid.
{
   return post ? post->typeid : 0;
 }
int getScoreP (MYPOST post)
Função que obtém o score de um post.
Parameters
post Apontador para a struct do post.
Returns
Score do post dado.
Definition at line 544 of file mypost.c.
References mypost::score.
{
       return post ? post->score : 0;
 }
char** getTagsP (MYPOST post)
Função que obtém as tags de um post.
Parameters
post Apontador para a struct do post.
Returns
Array de Tags do post dado.
Definition at line 421 of file mypost.c.
References mystrdup(), and mypost::tags.
{
   if(post){
     if(post->tags == NULL)
       return NULL;
     int i ;
     char ** tags;
     for(i= 0; post->tags[i] != NULL; i++)
       ;
       tags = malloc(sizeof(char *)*(i + 1));
     for(i= 0; post->tags[i] != NULL; i++){
       tags[i] = mystrdup(post->tags[i]);
     }
     tags[i] = NULL;
     return tags;
   }
   return NULL;
 }
char* getTitleP (MYPOST post)
Função que obtém o título de um post.
Parameters
post Apontador para a struct do post.
Returns
Title do post dado.
Definition at line 403 of file mypost.c.
References mystrdup(), and mypost::title.
{
   return post ? mystrdup(post->title) : NULL;
 }
int getTYPECLONEP (MYPOST post)
Função que verifica se um post é clone ou não.
Parameters
post Apontador para a struct do post.
Definition at line 325 of file mypost.c.
References mypost::type.
{
   return post ? post->type : 0;
 }
void incCounter1_STACKPOST (STACKPOST st, long i)
Função que adiciona um valor ao counter1.
Parameters
st STACKPOST.
i Conter 1.
Definition at line 159 of file mypost.c.
References stackpost::counter1.
{
   if (st){
     st->counter1 += i;
   }
 }
void incCounter2_STACKPOST (STACKPOST st, long i)
Função que adiciona um valor ao counter2.
Parameters
st STACKPOST.
i Conter 2.
Definition at line 148 of file mypost.c.
References stackpost::counter2.
{
   if (st){
     st->counter2 += i;
   }
 }
STACKPOST initSTACKPOST (long size)
Função que inicializa um stackpost.
Parameters
size Tamanho original da stackpost.
Returns
Apontador para a estrutura inicializada.
Definition at line 132 of file mypost.c.
References stackpost::array, stackpost::counter1, stackpost::counter2, stackpost::n_elem, and stackpost::size.
{
   STACKPOST a = malloc(sizeof(struct stackpost));
   a->counter1 = 0;
   a->counter2 = 0;
   a->n_elem = 0;
   a->size = size;
   a->array = malloc(size*sizeof(struct mypost *));
   return a;
 }
void insere_sem_rep_STACKPOST (STACKPOST st, MYPOST post)
Função que insere um elemento sem repetidos numa stackpost.
Parameters
st STACKPOST.
post Post a inserir.
Definition at line 216 of file mypost.c.
References stackpost::array, getIdP(), stackpost::n_elem, and stackpost::size.
{
   long i;
   MYPOST * aux;
   if (st->n_elem >= st->size){
     st->size *= 2;
     aux = malloc(st->size*sizeof(struct mypost *));
     for(i=0; i < st->n_elem; i++)
       aux[i] = st->array[i];
     free(st->array);
     st->array = aux;
   }
   for(i=0; i < st->n_elem ; i++){
     if (getIdP(post) == getIdP(st->array[i]))
       break;
   }
   if (i == st->n_elem)
     st->array[st->n_elem++] = post;
 }
void insereSTACKPOST (STACKPOST st, MYPOST post)
Função que insere um elemento numa stackpost.
Parameters
st STACKPOST.
post Post a inserir.
Definition at line 188 of file mypost.c.
References stackpost::array, stackpost::counter1, stackpost::counter2, getPostTypeIdP(), stackpost::n_elem, stackpost::size, and mypost::type.
{
   long i;
   int type = 0;
   MYPOST * aux;
   if (st->n_elem >= st->size){
     st->size *= 2;
     aux = malloc(st->size*sizeof(struct mypost *));
     for(i=0; i < st->n_elem; i++)
       aux[i] = st->array[i];
     free(st->array);
     st->array = aux;
   }
   st->array[st->n_elem++] = post;
   type = getPostTypeIdP(post);
   if (type == 1){
     st->counter1 += 1;
   }
   else if (type == 2){
     st->counter2 += 1;
   }
 }
int ordenaPOST_MYUSER (const void * data1, const void * data2)
Função que calcula o valor da nova ordenação.
Parameters
data1 MYPOST 1;
data2 MYPOST 2;
Returns
Inteiro usado como boolean.
Definition at line 63 of file mypost.c.
References mypost::cdate, and compare_MYDATE_AVL().
{
   MYPOST a1 = (MYPOST) data1;
   MYPOST a2 = (MYPOST) data2;
   int x = compare_MYDATE_AVL(a1->cdate,a2->cdate);
   return x;
 }
void order_STACKPOST (STACKPOST st, void * func)
Função que ordena uma stackpost.
Parameters
st STACKPOST.
func Função de comparação.
Definition at line 123 of file mypost.c.
References stackpost::array, stackpost::n_elem, and quicksort().
{
   quicksort(st->array,st->n_elem,func);
 }
void print_posts_MYPOST (MYPOST post)
Função que imprime os ids das respostas a um post.
Parameters
post Apontador para o post.
Definition at line 744 of file mypost.c.
References mypost::filhos, free_MYdate(), get_ele_index_STACKPOST(), get_MYday(), get_MYmonth(), get_MYyear(), getDateP(), getIdP(), and stackpost::n_elem.
{
   MYPOST post2 = NULL;
   MYDATE data = NULL;
   int i = 0;
   printf("Ne:%ld\n",post->filhos->n_elem);
   for(i=0; i < post->filhos->n_elem; i++){
     post2 = get_ele_index_STACKPOST(post->filhos,i);
     if (post2 != NULL){
       data = getDateP(post2);
       if (data != NULL){
         printf("Data-> D:%d M:%d A:%d || ID:%ld \n",get_MYday(data),get_MYmonth(data),get_MYyear(data), getIdP(post2));
         free_MYdate(data);
       }
     }
   }
   printf("I=%d\n",i);
 }
STACKPOST search_POSTDATA (TREE tree, MYDATE data)
MYPOST search_POSTID (TREE tree, long id)
Função que procura um post pelo id na estrutura com clone.
Parameters
tree Apontador para a árvore onde procurar o post.
id Id do post a procurar.
Returns
Apontador para o user que foi procurado, retorna NULL caso nao seja encontrado.
Definition at line 715 of file mypost.c.
References clone_MYPOST_DEEP(), and search_AVL().
{
   int valid;
   MYPOST post = search_AVL(tree, &id, &valid);
   if (valid)
     return clone_MYPOST_DEEP(post);
   return NULL;
 }
void setFilhosNoPost (MYPOST post, MYPOST data)
Função mete um post nos filhos desse mesmo post.
Parameters
post Identificador do post.
data Informação do post.
Definition at line 572 of file mypost.c.
References mypost::filhos, and insereSTACKPOST().
{
     if (post == NULL)
       return;
     insereSTACKPOST(post->filhos,data);
 }
int trans_arr (STACKPOST arr, int(*)(void *, void *, void *, void *, void *) f_box, void * data1, void * data2, void * data3, void * data4)
Função percorre um array e aplica a cada nodo uma função.
Parameters
arr Array a ser percorrido.
f_box Função a ser aplicada (cujo o primeiro argumento é o nodo a que ela é aplicada).
data1 Primeiro argumento da função a ser aplicada.
data2 Segundo argumento da função a ser aplicada.
data3 Terceiro argumento da função a ser aplicada.
data4 Quarto argumento da função a ser aplicada.
Returns
Inteiro usado como boolean.
Definition at line 45 of file mypost.c.
References stackpost::array, and stackpost::n_elem.
{
   if(arr == NULL)
     return 0;
   int flag = 0;
   for(int i = arr->n_elem - 1;i >= 0; i--)
     if(f_box((void *) arr->array[i],data1, data2, data3, data4))
       flag = 1;
   return flag;
 }
MYDATE xmlToMYDATE (char * value)
Função que processa a string correspondente ao valor Creation date e a transforma numa struct mydate.
Parameters
value A string com o valor CreationDate.
Returns
MYDATE convertida apos ler a string.
Definition at line 785 of file mypost.c.
References createMYDate().
{
   int yy, mm, dd;
   sscanf(value, "%d-%d-%dT", &yy, &mm ,&dd);
   MYDATE date = createMYDate(dd, mm, yy);
   return date;
 }
void xmltoMYPOST (MYPOST post, xmlNodePtr xml, xmlDocPtr doc, TREE treeid, TREE treeusers)
Função que copia informação de um nodo da estrutura do libxml2 para o análogo da nossa estrutura.
Parameters
post O apontador da nossa estrutura.
xml O apontador da estrutura resultante do parsing do ficheiro xml.
doc O apontador para o documento xml. (libxml2)
treeid O apontador para a àrvore de posts ordenada por id.
treeusers O apontador para a árvore de users.
Definition at line 850 of file mypost.c.
References free_MYdate(), free_StringArray(), search_POSTID_internal(), setAnswersP(), setCommentsP(), setDateP(), setFavsP(), setFilhosNoPost(), setIdP(), setOwnerIdP(), setOwnerNameP(), setPIdP(), setPostTypeIdP(), setScoreP(), setTagsP(), setTitleP(), xmlToMYDATE(), and xmlToStringArray().
{
   xmlAttrPtr cur;
   char flag[12] = {0};  //flags para não estar constantemente a chamar a strcmp()
   char * value;
   char ** arr;
   MYDATE date;
   MYPOST parent = NULL;
   long l;
   for(cur = xml->properties; cur; cur = cur->next) {
         value = (char *) xmlNodeListGetString(doc, cur->children, 1);
         if(!flag[0] && strcmp((char *) cur->name, "Id") == 0) {
           setIdP(post, atol(value));
           flag[0] = 1;
           free(value);
           continue;
         }
         if(!flag[1] && strcmp((char *) cur->name, "PostTypeId") == 0) {
           setPostTypeIdP(post, atoi(value));
           flag[1] = 1;
           free(value);
           continue;
         }
         if(!flag[2] && strcmp((char *) cur->name, "ParentId") == 0) {
           l = atol(value);
           parent = search_POSTID_internal(treeid, l);
           setPIdP(post, l);
           flag[2] = 1;
           free(value);
           continue;
         }
         if(!flag[3] && strcmp((char *) cur->name, "CreationDate") == 0) {
           date = xmlToMYDATE(value);
           setDateP(post, date);
           flag[3] = 1;
           free(value);
           free_MYdate(date);
           continue;
         }
         if(!flag[4] && strcmp((char *) cur->name, "Score") == 0) {
           setScoreP(post, atoi(value));
           flag[4] = 1;
           free(value);
           continue;
         }
         if(!flag[5] && strcmp((char *) cur->name, "OwnerUserId") == 0) {
           l = atol(value);
           setOwnerIdP(post, l);
           flag[5] = 1;
           free(value);
           continue;
         }
         if(!flag[6] && strcmp((char *) cur->name, "OwnerDisplayName") == 0) {
           setOwnerNameP(post, value);
           flag[6] = 1;
           free(value);
           continue;
         }
         if(!flag[7] && strcmp((char *) cur->name, "Title") == 0) {
           setTitleP(post, value);
           flag[7] = 1;
           free(value);
           continue;
         }
         if(!flag[8] && strcmp((char *) cur->name, "Tags") == 0) {
           arr = xmlToStringArray(value);
           setTagsP(post, arr);
           flag[8] = 1;
           free(value);
           free_StringArray(arr);
           continue;
         }
         if(!flag[9] && strcmp((char *) cur->name, "AnswerCount") == 0) {
           setAnswersP(post, atoi(value));
           flag[9] = 1;
           free(value);
           continue;
         }
         if(!flag[10] && strcmp((char *) cur->name, "CommentCount") == 0) {
           setCommentsP(post, atoi(value));
           flag[10] = 1;
           free(value);
           continue;
         }
         if(!flag[11] && strcmp((char *) cur->name, "FavoriteCount") == 0) {
           setFavsP(post, atoi(value));
           flag[11] = 1;
           free(value);
           continue;
         }
         free(value);
   }
   if(parent)
     setFilhosNoPost(parent,post);
 }
char** xmlToStringArray (char * value)
Função que processa a string correspondente ao valor Tags a transforma num array de strings.
Parameters
value A string com o valor Tags.
Returns
Arrays de Strings obtidos apos leitura da string.
Definition at line 802 of file mypost.c.
{
   int i, n = strlen(value);
   int tag_counter = 0;
   for(i = 0; i < n; i++)                  //Conta o número de tags
     if(value[i] == '<')
       tag_counter++;
   if(tag_counter == 0)                  //Retorna NULL se não há tags
     return NULL;
   char ** arr = malloc((tag_counter + 1)*sizeof(char *)); //Aloca memória para o numero de apontadores necessários para as tags.
   int j = 0, k = 0;
   int starts[tag_counter];
   char format[10];
   for(i = 0; i < n; i++) {                //Percrre a string value que contém as tags
     if(value[i] == '<') {               //Se for  início de outra tag, dá reset ao contador de tamanho
       j = 0;                      //regista o início desta tag
       starts[k] = i + 1;
     }
     else if (value[i] == '>') {             //Se for o fim de uma tag
       arr[k] = malloc((sizeof(char) + 1)*j);      //Aloca a memória necessária para a mesma
       sprintf(format, "%%%ds", j);          //Regista o formato auxiliar ao sscanf
       sscanf(&value[starts[k]], format, arr[k]);    //Copia a tag para a string do array
       arr[k][j] = '\0';               //Sinaliza o final da string de cada tag com EOF.
       k++;                      //Incrementa o índice do array de strings
     }
     else
       j++;                      //Incrementa o registo do tamanho da tag atual
   }
   arr[k] = NULL;                      //O último apontador deste array aponta para NULL
   return arr;
 }