ProjetoLI3: mytree.c File Reference
mytree.c File Reference
Ficheiro contendo funções utilizadas na construção da AVL utilizada no programa bem como todas as funcionalidades pela mesma suportadas.
#include "mytree.h"
Classes
struct AVBin
struct tree
Macros
#define MAX(a, b) a > b ? a : b;
#define MAX_SIZE 40
Typedefs
typedef struct AVBin * AVL
Functions
static int altura (AVL a)
Função calcula a altura de um nodo.
static int balanceDEEP (AVL a)
Função calcula o balanço de um nodo.
static int cal_altura (AVL a)
Função calcula a altura de uma árvore.
static int isBalanced (AVL a)
Função verifica se a árvore é balanceada.
int TREE_balance (TREE tre)
Função verifica se a arvore da estrutura é balanceada.
static AVL rotate_rigth (AVL a)
Função efetua uma rotação para a direita da árvore.
static AVL rotate_left (AVL a)
Função efetua uma rotação para a esquerda da árvore.
static AVL balance (AVL a)
Função efetua o balanceamento da árvore.
static void implementa_alt (AVL *a)
Função que implementa a nova altura de um dado nodo.
static AVL create_new_node (void *key, void *data)
Função que cria um novo nodo.
TREE insere_tree (TREE gl, void *key, void *data)
Função insere um elemento na árvore.
TREE createTREE (void *f_compare, void *destroy_key, void *destroy_data, void *replace)
Função cria a estrutura que contêm a árvore.
static void freeAVL (AVL a, void(*destroy_key)(void *), void(*destroy_data)(void *))
Função liberta a memória de uma AVL.
void freeTREE_AVL (TREE tre)
Função liberta a memória da estrutura Tree.
void * search_AVL (TREE tree, void *key, int *valid)
Função que procura um elemento na árvore.
static int check_altura (AVL a)
Função que testa se os nodos da AVL têm as alturas direitas.
static int isSearch (AVL a, TREE tree)
Função que testa a AVL é de procura.
static void all_nodes_trans (AVL aux, void(*f_nodo)(void *, void *), void *data1)
Função que vai ser aplicada a todos os nodos.
void all_nodes_TREE (TREE e, void(*f_nodo)(void *, void *), void *data1)
Função que vai ser aplicada a todos os nodos.
static void all_nodes_With_key_Condition (AVL aux, void *inicio, void *fim, int(*f_compare)(void *, void *), void(*f_nodo)(void *, void *, void *), void *data3, void *data4)
Função que aplica uma função aos nodos que satisfazem uma condição.
void all_nodes_With_Condition (TREE tree, void *data1, void *data2, void(*f_nodo)(void *, void *, void *), void *data3, void *data4)
Função que aplica uma função aos nodos que satisfazem uma condição.
int test_TREE_PROP (TREE tree)
Função que testa as propriedas da tree.
long NUM_nodes (TREE t)
Função que devolve o número de nodos da árvore.
static void trans_inorder (AVL aux, void(*f_nodo)(void *, void *, void *, void *), void *data1, void *data2, void *begin, void *end, int *n)
Função que faz uma travessia inorder na árvore.
static void trans_revinorder (AVL aux, void(*f_nodo)(void *, void *, void *, void *), void *data1, void *data2, void *begin, void *end, int *n)
Função que faz uma travessia revinorder na árvore.
static void trans_posorder (AVL aux, void(*f_nodo)(void *, void *, void *, void *), void *data1, void *data2, void *begin, void *end, int *n)
Função que faz uma travessia postorder na árvore.
static void trans_preorder (AVL aux, void(*f_nodo)(void *, void *, void *, void *), void *data1, void *data2, void *begin, void *end, int *n)
Função que faz uma travessia preorder na árvore.
static void trans_4_args (AVL aux, void(*f_nodo)(void *, void *, void *, void *), void *data1, void *data2, void *begin, void *end)
Função que faz uma travessia na árvore com 4 argumentos.
void trans_tree (TREE e, void(*f_nodo)(void *, void *, void *, void *), void *data1, void *data2, void *begin, void *end, int travessia, int n)
Função que faz uma travessia na árvore.
Detailed Description
Ficheiro contendo funções utilizadas na construção da AVL utilizada no programa bem como todas as funcionalidades pela mesma suportadas.
Definition in file mytree.c.
Macro Definition Documentation
#define MAX (a, b) a > b ? a : b;
Definition at line 8 of file mytree.c.
#define MAX_SIZE 40
Definition at line 9 of file mytree.c.
Typedef Documentation
typedef struct AVBin* AVL
Definition at line 18 of file mytree.c.
Function Documentation
static void all_nodes_trans (AVL aux, void(*)(void *, void *) f_nodo, void * data1) static
Função que vai ser aplicada a todos os nodos.
Parameters
aux Apontador para a arvore.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar à função a aplicar.
Definition at line 423 of file mytree.c.
References AVBin::data, AVBin::dir, and AVBin::esq.
{
   if (aux){
     f_nodo(aux->data,data1);
     all_nodes_trans(aux->esq,f_nodo,data1);
     all_nodes_trans(aux->dir,f_nodo,data1);
   }
 }
void all_nodes_TREE (TREE e, void(*)(void *, void *) f_nodo, void * data1)
Função que vai ser aplicada a todos os nodos.
Parameters
e Apontador para a estrutura que contem a AVL.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar à função a aplicar.
Definition at line 437 of file mytree.c.
References all_nodes_trans(), and tree::arv.
{
   if (f_nodo != NULL)
     all_nodes_trans(e->arv,f_nodo,data1);
 }
void all_nodes_With_Condition (TREE tree, void * data1, void * data2, void(*)(void *, void *, void *) f_nodo, void * data3, void * data4)
Função que aplica uma função aos nodos que satisfazem uma condição.
Parameters
tree Apontador para a estrutura que contém a árvore.
data1 Apontador para a data1 a comparar.
data2 Apontador para a data2 a comparar.
f_nodo Função a aplicar em todos os nodos.
data3 Aparametro 1 a passar à função que aplica nos nodos.
data4 Aparametro 2 a passar à função que aplica nos nodos.
Definition at line 478 of file mytree.c.
References all_nodes_With_key_Condition(), tree::arv, and tree::f_compare.
{
   all_nodes_With_key_Condition(tree->arv,data1,data2,tree->f_compare,f_nodo,data3,data4);
 }
static void all_nodes_With_key_Condition (AVL aux, void * inicio, void * fim, int(*)(void *, void *) f_compare, void(*)(void *, void *, void *) f_nodo, void * data3, void * data4) static
Função que aplica uma função aos nodos que satisfazem uma condição.
Parameters
aux Apontador para a AVL.
inicio Apontador para a data1 a comparar.
fim Apontador para a data2 a comparar.
f_compare Apontador para a função que compara.
f_nodo Função a aplicar em todos os nodos.
data3 Aparametro 1 a passar à função que aplica nos nodos.
data4 Aparametro 2 a passar à função que aplica nos nodos.
Definition at line 452 of file mytree.c.
References AVBin::data, AVBin::dir, AVBin::esq, and AVBin::key.
{
   int a1,a2;
   if(aux){
     a1 =f_compare(inicio,aux->key);
     a2 =f_compare(fim,aux->key);
     if ((a1 > 0 && a2 < 0) || (a1==0) || (a2==0)){
       all_nodes_With_key_Condition(aux->esq,inicio,fim,f_compare,f_nodo,data3,data4);
       f_nodo(aux->data,data3,data4);
       all_nodes_With_key_Condition(aux->dir,inicio,fim,f_compare,f_nodo,data3,data4);
     }
     else if (a1 > 0)
       all_nodes_With_key_Condition(aux->esq,inicio,fim,f_compare,f_nodo,data3,data4);
     else if (a2 < 0)
       all_nodes_With_key_Condition(aux->dir,inicio,fim,f_compare,f_nodo,data3,data4);
   }
 }
static int altura (AVL a) static
Função calcula a altura de um nodo.
Parameters
a Apontador para a árvore.
Returns
Altura de um nodo.
Definition at line 35 of file mytree.c.
References AVBin::altura.
{
     return a ? a-> altura : 0;
 }
static AVL balance (AVL a) static
Função efetua o balanceamento da árvore.
Parameters
a Apontador para a árvore.
Returns
Árvore balanceada.
Definition at line 153 of file mytree.c.
References AVBin::altura, balanceDEEP(), AVBin::dir, AVBin::esq, rotate_left(), and rotate_rigth().
{
     int hd, hl;
     hd = altura(a->dir);
     hl = altura(a->esq);
     int bal = hd -hl;
     if (bal == -2){
         if (balanceDEEP(a->esq) == 1)
             a->esq = rotate_left(a->esq);
         a = rotate_rigth(a);
     }
     if (bal == 2){
         if (balanceDEEP(a->dir) == -1)
             a->dir = rotate_rigth(a->dir);
         a = rotate_left(a);
     }
     return a;
 }
static int balanceDEEP (AVL a) static
Função calcula o balanço de um nodo.
Parameters
a Apontador para a árvore.
Returns
Inteiro com o valor do balanço.
Definition at line 44 of file mytree.c.
References AVBin::altura, balance(), AVBin::dir, and AVBin::esq.
{
     int balance = 0;
     if (a){
         balance = altura(a->dir) - altura(a->esq);
     }
     return balance;
 }
static int cal_altura (AVL a) static
Função calcula a altura de uma árvore.
Parameters
a Apontador para a árvore.
Returns
Altura da árvore.
Definition at line 58 of file mytree.c.
References AVBin::dir, and AVBin::esq.
{
     int h = 0;
     int h1, h2;
     if(a){
         h1 = cal_altura(a->esq);
         h2 = cal_altura(a->dir);
         h = h1 > h2 ? h1 + 1 : h2 +1;
     }
     return h;
 }
static int check_altura (AVL a) static
Função que testa se os nodos da AVL têm as alturas direitas.
Parameters
a Apontador para a AVL.
Returns
Inteiro a ser usado como booelan.
Definition at line 382 of file mytree.c.
References AVBin::altura, cal_altura(), AVBin::dir, and AVBin::esq.
{
     int r = 1;
     int b;
     if (a){
         b = cal_altura(a);
         if (a->altura == b){
             r = cal_altura(a->esq) && cal_altura(a->dir);
         }
     }
     return r;
 }
static AVL create_new_node (void * key, void * data) static
Função que cria um novo nodo.
Parameters
key Apontador a key.
data Apontador para a data.
Returns
Apontador para o nodo da árvore.
Definition at line 198 of file mytree.c.
References AVBin::altura, AVBin::data, AVBin::dir, AVBin::esq, and AVBin::key.
{
     AVL a;
     a = malloc(sizeof(struct AVBin));
     a -> altura = 1;
     a -> key = key;
   a -> data = data;
     a -> esq = NULL;
     a -> dir = NULL;
     return a;
 }
TREE createTREE (void * f_compare, void * destroy_key, void * destroy_data, void * replace)
Função cria a estrutura que contêm a árvore.
Parameters
f_compare Apontador para a função de comparação.
destroy_key Apontador para a função que dá free à key.
destroy_data Apontador para a função que dá free à data.
replace Apontador para a função que dá replace à informação.
Returns
Apontador para a estrutura criada.
Definition at line 302 of file mytree.c.
References tree::arv, tree::destroy_data, tree::destroy_key, tree::f_compare, tree::heigth, tree::nnodes, and tree::replace_fun.
{
     TREE a = malloc(sizeof(struct tree));
     a->nnodes = 0;
     a->heigth = 0;
     a->arv = NULL;
   a->replace_fun = replace;
     a->f_compare = f_compare;
   a->destroy_key = destroy_key;
   a->destroy_data = destroy_data;
     return a;
 }
static void freeAVL (AVL a, void(*)(void *) destroy_key, void(*)(void *) destroy_data) static
Função liberta a memória de uma AVL.
Parameters
a Apontador para a AVL.
destroy_key Apontador para a função que destroi a key.
destroy_data Apontador para a função que destroi a data.
Definition at line 321 of file mytree.c.
References AVBin::data, AVBin::dir, AVBin::esq, and AVBin::key.
{
   if (a){
     if (destroy_key != NULL)
       destroy_key(a->key);
     if (destroy_data != NULL)
       destroy_data(a->data);
     freeAVL(a->esq,destroy_key,destroy_data);
     freeAVL(a->dir,destroy_key,destroy_data);
     free(a);
   }
 }
void freeTREE_AVL (TREE tre)
Função liberta a memória da estrutura Tree.
Parameters
tree Apontador para a tree.
Definition at line 341 of file mytree.c.
References tree::arv, tree::destroy_data, tree::destroy_key, and freeAVL().
{
   if(tre){
     freeAVL(tre->arv,tre->destroy_key,tre->destroy_data);
     free(tre);
   }
 }
static void implementa_alt (AVL * a) static
Função que implementa a nova altura de um dado nodo.
Parameters
a Apontador para a árvore.
Definition at line 181 of file mytree.c.
References AVBin::altura, AVBin::dir, and AVBin::esq.
{
     int hl,hr;
     AVL aux = * a;
     hr = altura(aux->dir);
     hl = altura(aux->esq);
     aux->altura = hr > hl ? hr + 1 : hl + 1;
 }
TREE insere_tree (TREE gl, void * key, void * data)
Função insere um elemento na árvore.
Parameters
gl Apontador para a estrutura que guarda a árvore.
key Apontador para a key a inserir.
data Apontador para a data a inserir.
Returns
Apontador para a estrutura após ser inserido o valor.
Definition at line 217 of file mytree.c.
References AVBin::altura, tree::arv, balance(), create_new_node(), AVBin::data, tree::destroy_key, AVBin::dir, AVBin::esq, tree::f_compare, implementa_alt(), AVBin::key, MAX_SIZE, tree::nnodes, and tree::replace_fun.
{
     AVL queue[MAX_SIZE];
     AVL a = gl->arv;
   int replace = 0;
   int side;
     int idx = 0;
     queue[idx++] = NULL;
     if (!a){
         a = create_new_node(key,data);
     gl->arv = a;
     }
     else{
         while(1){
       side = (gl->f_compare(a->key,key));
       if (side == 0){
         if (gl->replace_fun != NULL){
           replace = 1;
           a->data=gl->replace_fun(a->data,data);
           if (gl->destroy_key != NULL)
             gl->destroy_key(key);
           break;
         }
       }
             if (side > 0){
                 if (a->dir){
                     queue[idx++] = a;
                     a = a->dir;
                 }
                 else {
                     a->dir = create_new_node(key,data);
                     break;
                 }
             }
             else {
                 if (a->esq){
                     queue[idx++] = a;
                     a = a->esq;
                 }
                 else{
                     a->esq = create_new_node(key,data);
                     break;
                 }
             }
         }
         AVL pai;
         int check_side, balan;
     if (replace == 0){
           while(1){
               pai = queue[--idx];
               check_side = ((!pai) ||pai->esq == a);
               implementa_alt(&a);
               balan = altura(a->dir) - altura(a->esq);
               if (balan < -1 || balan > 1){
                   a = balance(a);
                   if (!pai)
                       break;
                   else if (check_side)
                       pai->esq = a;
                   else pai->dir = a;
               }
               if(!pai)
                   break;
               a = pai;
           }
       gl->arv = a;
     }
     }
   gl->nnodes++;
     return gl;
 }
static int isBalanced (AVL a) static
Função verifica se a árvore é balanceada.
Parameters
a Apontador para a árvore.
Returns
Inteiro a ser usado como boolean.
Definition at line 76 of file mytree.c.
References cal_altura(), AVBin::dir, and AVBin::esq.
{
     int r = 1;
     int b;
     if(a){
         b = cal_altura(a->dir) - cal_altura(a->esq);
         if ((b >= -1) && (b <= 1))
             r = isBalanced(a->esq) && isBalanced(a->dir);
         else r = 0;
     }
     return r;
 }
static int isSearch (AVL a, TREE tree) static
Função que testa a AVL é de procura.
Parameters
a Apontador para a AVL.
tree Apontador para a estrutura com a função de comparação.
Returns
Inteiro a ser usado como booelan.
Definition at line 401 of file mytree.c.
References AVBin::dir, AVBin::esq, tree::f_compare, and AVBin::key.
{
     int r = 1;
     if (a){
         if (a->dir == NULL && a->esq == NULL)
             r = 1;
         else if (a->dir == NULL && (tree->f_compare(a->key,a->esq->key) < 0))
             r = isSearch(a->esq,tree);
         else if (a->esq == NULL && (tree->f_compare(a->key,a->dir->key) > 0))
             r = isSearch(a->dir,tree);
         else if ((tree->f_compare(a->key,a->dir->key) > 0) && (tree->f_compare(a->key,a->esq->key) < 0))
             r = isSearch(a->dir,tree) && isSearch(a->esq,tree);
         else r = 0;
     }
     return r;
 }
long NUM_nodes (TREE t)
Função que devolve o número de nodos da árvore.
Parameters
tree Estrutura que contém a árvore.
Returns
Numero de nodos da árvore.
Definition at line 502 of file mytree.c.
References tree::nnodes.
                       {
   return t->nnodes;
 }
static AVL rotate_left (AVL a) static
Função efetua uma rotação para a esquerda da árvore.
Parameters
a Apontador para a árvore.
Returns
Árvore após ser rodada para a esquerda.
Definition at line 128 of file mytree.c.
References AVBin::altura, AVBin::dir, and AVBin::esq.
{
     int ha_r, ha_l;
     AVL aux = a->dir;
     a->dir = aux -> esq;
     aux->esq = a;
     ha_l = altura(a->esq);
     ha_r = altura(a->dir);
     a->altura = ha_r > ha_l ? ha_r + 1 : ha_l + 1;
     ha_r = altura(aux->dir);
     ha_l = a->altura;
     aux->altura = ha_r > ha_l ? ha_r + 1 : ha_l + 1;
     return aux;
 }
static AVL rotate_rigth (AVL a) static
Função efetua uma rotação para a direita da árvore.
Parameters
a Apontador para a árvore.
Returns
Árvore após ser rodada para a direita.
Definition at line 103 of file mytree.c.
References AVBin::altura, AVBin::dir, and AVBin::esq.
{
     int ha_r, ha_l;
     AVL aux = a -> esq;
     a->esq = aux -> dir;
     aux -> dir = a;
     ha_r = altura(a->dir);
     ha_l = altura(a->esq);
     a->altura = ha_r > ha_l ? ha_r + 1 : ha_l + 1;
     ha_l = altura(aux->esq);
     ha_r = a->altura;
     aux->altura = ha_r > ha_l ? ha_r + 1 : ha_l + 1;
     return aux;
 }
void* search_AVL (TREE tree, void * key, int * valid)
Função que procura um elemento na árvore.
Parameters
tree Estrutura que contém a árvore.
key Apontador para a key a procurar.
valid Apontador para o passar o resultado da procura.
Returns
Data da árvore apos ser procurado o elemento, retorna NULL caso falhe na procura.
Definition at line 359 of file mytree.c.
References tree::arv, AVBin::data, AVBin::dir, AVBin::esq, tree::f_compare, and AVBin::key.
{
   AVL node = tree->arv;
   int result = 0;
   while((!result) && node){
     if (tree->f_compare(node->key,key) == 0){
       result = 1;
     }
     else if (tree->f_compare(node->key,key) == 1)
       node = node->dir;
     else node = node ->esq;
   }
   *valid = result;
   if (result)
     return node->data;
   return NULL;
 }
int test_TREE_PROP (TREE tree)
Função que testa as propriedas da tree.
Parameters
tree Estrutura que contém a árvore.
Returns
Inteiro a ser usado como booelan.
Definition at line 488 of file mytree.c.
References tree::arv, check_altura(), isBalanced(), and isSearch().
{
   int alturas,procura,balanceada;
   balanceada = isBalanced(tree->arv);
   alturas = check_altura(tree->arv);
   procura = isSearch(tree->arv,tree);
   return balanceada && alturas && procura;
 }
static void trans_4_args (AVL aux, void(*)(void *, void *, void *, void *) f_nodo, void * data1, void * data2, void * begin, void * end) static
Função que faz uma travessia na árvore com 4 argumentos.
Parameters
aux Apontador para a arvore.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar como argumento à função a aplicar.
data2 Apontador a passar como argumento à função a aplicar.
begin Data início do intervalo a que o nodo tem de pertencer. (nullable)
end Data início do intervalo a que o nodo tem de pertencer. (nullable)
n Número máximo de nodos a percorrer. (nullable)
Definition at line 659 of file mytree.c.
References compare_MYDATE_AVL(), AVBin::data, AVBin::dir, AVBin::esq, and AVBin::key.
{
   if (aux){
     if (begin == NULL || end == NULL) {
       trans_4_args(aux->esq,f_nodo,data1, data2, begin, end);
       f_nodo(aux->data,data1, begin,end);
       trans_4_args(aux->dir,f_nodo,data1, data2, begin, end);
     }
     else {
       int r1 = compare_MYDATE_AVL((MYDATE) begin, (MYDATE) aux->key );
       int r2 = compare_MYDATE_AVL((MYDATE) end, (MYDATE) aux->key);
       if(r1 >= 0 && r2 <= 0) {
         trans_4_args(aux->esq,f_nodo,data1, data2, begin, end);
         f_nodo(aux->data,data1, begin,end);
         trans_4_args(aux->dir,f_nodo,data1, data2, begin, end);
       }
       else if (r1 >= 0)
         trans_4_args(aux->esq,f_nodo,data1, data2, begin, end);
       else if (r2 <= 0)
         trans_4_args(aux->dir,f_nodo,data1, data2, begin, end);
     }
   }
 }
static void trans_inorder (AVL aux, void(*)(void *, void *, void *, void *) f_nodo, void * data1, void * data2, void * begin, void * end, int * n) static
Função que faz uma travessia inorder na árvore.
Parameters
aux Apontador para a arvore.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar como argumento à função a aplicar.
data2 Apontador a passar como argumento à função a aplicar.
begin Data início do intervalo a que o nodo tem de pertencer. (nullable)
end Data início do intervalo a que o nodo tem de pertencer. (nullable)
n Número máximo de nodos a percorrer. (nullable)
Definition at line 516 of file mytree.c.
References compare_MYDATE_AVL(), AVBin::data, AVBin::dir, AVBin::esq, and AVBin::key.
{
   if (aux){
     if (begin == NULL || end == NULL) {
       trans_inorder(aux->esq,f_nodo,data1, data2, begin, end, n);
       f_nodo(aux->data,data1, data2, n);
       trans_inorder(aux->dir,f_nodo,data1, data2, begin, end, n);
     }
     else {
       int r1 = compare_MYDATE_AVL((MYDATE) begin, (MYDATE) aux->key );
       int r2 = compare_MYDATE_AVL((MYDATE) end, (MYDATE) aux->key);
       if(r1 >= 0 && r2 <= 0) {
         trans_inorder(aux->esq,f_nodo,data1, data2, begin, end, n);
         f_nodo(aux->data,data1, data2, n);
         trans_inorder(aux->dir,f_nodo,data1, data2, begin, end, n);
       }
       else if (r1 >= 0)
         trans_inorder(aux->esq,f_nodo,data1, data2, begin, end, n);
       else if (r2 <= 0)
         trans_inorder(aux->dir,f_nodo,data1, data2, begin, end, n);
     }
   }
 }
static void trans_posorder (AVL aux, void(*)(void *, void *, void *, void *) f_nodo, void * data1, void * data2, void * begin, void * end, int * n) static
Função que faz uma travessia postorder na árvore.
Parameters
aux Apontador para a arvore.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar como argumento à função a aplicar.
data2 Apontador a passar como argumento à função a aplicar.
begin Data início do intervalo a que o nodo tem de pertencer. (nullable)
end Data início do intervalo a que o nodo tem de pertencer. (nullable)
n Número máximo de nodos a percorrer. (nullable)
Definition at line 586 of file mytree.c.
References compare_MYDATE_AVL(), AVBin::data, AVBin::dir, AVBin::esq, and AVBin::key.
{
   if (aux){
     if (*n <= 0)
       return;
     if (begin == NULL || end == NULL) {
       trans_posorder(aux->esq,f_nodo,data1, data2, begin, end, n);
       trans_posorder(aux->dir,f_nodo,data1, data2, begin, end, n);
       f_nodo(aux->data,data1, data2, n);
     }
     else {
       int r1 = compare_MYDATE_AVL((MYDATE) begin, (MYDATE) aux->key );
       int r2 = compare_MYDATE_AVL((MYDATE) end, (MYDATE) aux->key);
       if(r1 >= 0 && r2 <= 0) {
         trans_posorder(aux->esq,f_nodo,data1, data2, begin, end, n);
         trans_posorder(aux->dir,f_nodo,data1, data2, begin, end, n);
         f_nodo(aux->data,data1, data2, n);
       }
       else if (r1 >= 0)
         trans_posorder(aux->esq,f_nodo,data1, data2, begin, end, n);
       else if (r2 <= 0)
         trans_posorder(aux->dir,f_nodo,data1, data2, begin, end, n);
     }
   }
 }
static void trans_preorder (AVL aux, void(*)(void *, void *, void *, void *) f_nodo, void * data1, void * data2, void * begin, void * end, int * n) static
Função que faz uma travessia preorder na árvore.
Parameters
aux Apontador para a arvore.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar como argumento à função a aplicar.
data2 Apontador a passar como argumento à função a aplicar.
begin Data início do intervalo a que o nodo tem de pertencer. (nullable)
end Data início do intervalo a que o nodo tem de pertencer. (nullable)
n Número máximo de nodos a percorrer. (nullable)
Definition at line 621 of file mytree.c.
References compare_MYDATE_AVL(), AVBin::data, AVBin::dir, AVBin::esq, AVBin::key, and trans_posorder().
{
   if (aux){
     if (*n <= 0)
       return;
     if (begin == NULL || end == NULL) {
       f_nodo(aux->data,data1, data2, n);
       trans_posorder(aux->esq,f_nodo,data1, data2, begin, end, n);
       trans_posorder(aux->dir,f_nodo,data1, data2, begin, end, n);
     }
     else {
       int r1 = compare_MYDATE_AVL((MYDATE) begin, (MYDATE) aux->key );
       int r2 = compare_MYDATE_AVL((MYDATE) end, (MYDATE) aux->key);
       if(r1 >= 0 && r2 <= 0) {
         f_nodo(aux->data,data1, data2, n);
         trans_preorder(aux->esq,f_nodo,data1, data2, begin, end, n);
         trans_preorder(aux->dir,f_nodo,data1, data2, begin, end, n);
       }
       else if (r1 >= 0)
         trans_preorder(aux->esq,f_nodo,data1, data2, begin, end, n);
       else if (r2 <= 0)
         trans_preorder(aux->dir,f_nodo,data1, data2, begin, end, n);
     }
   }
 }
static void trans_revinorder (AVL aux, void(*)(void *, void *, void *, void *) f_nodo, void * data1, void * data2, void * begin, void * end, int * n) static
Função que faz uma travessia revinorder na árvore.
Parameters
aux Apontador para a arvore.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar como argumento à função a aplicar.
data2 Apontador a passar como argumento à função a aplicar.
begin Data início do intervalo a que o nodo tem de pertencer. (nullable)
end Data início do intervalo a que o nodo tem de pertencer. (nullable)
n Número máximo de nodos a percorrer. (nullable)
Definition at line 550 of file mytree.c.
References compare_MYDATE_AVL(), AVBin::data, AVBin::dir, AVBin::esq, and AVBin::key.
{
   if (aux){
     if (*n <= 0)
       return;
     if (begin == NULL || end == NULL) {
       trans_revinorder(aux->dir,f_nodo,data1, data2, begin, end, n);
       f_nodo(aux->data,data1, data2, n);
       trans_revinorder(aux->esq,f_nodo,data1, data2, begin, end, n);
     }
     else {
       int r1 = compare_MYDATE_AVL((MYDATE) begin, (MYDATE) aux->key );
       int r2 = compare_MYDATE_AVL((MYDATE) end, (MYDATE) aux->key);
       if(r1 >= 0 && r2 <= 0) {
         trans_revinorder(aux->dir,f_nodo,data1, data2, begin, end, n);
         f_nodo(aux->data,data1, data2, n);
         trans_revinorder(aux->esq,f_nodo,data1, data2, begin, end, n);
       }
       else if (r1 >= 0)
         trans_revinorder(aux->esq,f_nodo,data1, data2, begin, end, n);
       else if (r2 <= 0)
         trans_revinorder(aux->dir,f_nodo,data1, data2, begin, end, n);
     }
   }
 }
void trans_tree (TREE e, void(*)(void *, void *, void *, void *) f_nodo, void * data1, void * data2, void * begin, void * end, int travessia, int n)
Função que faz uma travessia na árvore.
Parameters
e Apontador para a arvore.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar como argumento à função a aplicar.
data2 Apontador a passar como argumento à função a aplicar.
begin Data início do intervalo a que o nodo tem de pertencer. (nullable)
end Data início do intervalo a que o nodo tem de pertencer. (nullable)
travessia Tipo de travessia.
n Número máximo de nodos a percorrer. (nullable)
Definition at line 694 of file mytree.c.
References tree::arv, trans_4_args(), trans_inorder(), trans_posorder(), trans_preorder(), and trans_revinorder().
{
   if (!e)
     return;
   if (travessia == 1)
     trans_posorder(e->arv,f_nodo,data1, data2, begin, end, &n);
   else if (travessia == 2)
     trans_inorder(e->arv,f_nodo,data1, data2, begin, end, &n);
   else if (travessia == 3)
     trans_preorder(e->arv,f_nodo,data1, data2, begin, end, &n);
   else if (travessia == 4) {
     trans_revinorder(e->arv, f_nodo, data1, data2, begin, end, &n);
   }
   else if (travessia == 5){
     trans_4_args(e->arv, f_nodo, data1, data2, begin, end);
   }
 }
int TREE_balance (TREE tre)
Função verifica se a arvore da estrutura é balanceada.
Parameters
tree Apontador para a estrutura.
Returns
Inteiro a ser usado como boolean.
Definition at line 94 of file mytree.c.
References tree::arv, and isBalanced().
{
   return isBalanced(tre->arv);
 }