ProjetoLI3: myuser.c File Reference
myuser.c File Reference
Ficheiro contendo todas a funções relativa à estrutura MYUSER.
#include "myuser.h"
Classes
struct myuser
Functions
long getIdMYUSER (MYUSER use)
Função que devolve o id do user.
int getREPMYUSER (MYUSER use)
Função que devolve a rep do user.
char * getUsername (MYUSER use)
Função que devolve o Username do user.
char * getBiography (MYUSER use)
Função que devolve a biografia do user.
STACKPOST getMYLISTuser (MYUSER use)
Função que devolve a lista de posts de um USER.
long * getNposts (MYUSER use, int n, int *n_elem)
Função que devolve os ultimos N posts de um dado utilizador.
long getNUM_POST_MYUSER (MYUSER use)
Função que devolve o número de posts de um utilizador.
void print_post_MYUSER (MYUSER use)
Função que imprime os id dos post de um utilizador.
static void setIdUSER (MYUSER use, long id)
Função que altera o Id de um user.
static void setRp (MYUSER use, int rep)
Função que altera a reputação de um user.
static void setBio (MYUSER use, char *bio)
Função que altera a biografia de um user.
static void setUsername (MYUSER use, char *nome)
Função que obtém altera o nome de um user.
MYUSER createMYUSER (int type)
Função que aloca memória para um user.
MYUSER cloneMYUSER (MYUSER use)
Função que clona um user.
void freeMYUSER (void *aux)
Função que liberta a memória de um user.
int compare_user (void *key1, void *key2)
Função que compara 2 keys de user diferentes.
void freeKey (void *a)
Função que liberta a memória de um key.
void freeTreeUSER (TREE tree)
Função que liberta a memória da arvóre alocada.
MYUSER search_USER (TREE tree, long id)
Função que procura um user na estrutura com clone.
static MYUSER search_USER_internal (TREE tree, long id)
Função que procura um user na estrutura sem clone.
int setPostToUSER (TREE tree, long id, MYPOST data)
Função mete um post no correspondete user.
TREE createMYUSERS_TREE (char *path)
Função lê o ficheiro User.xml e cria uma arvore.
Detailed Description
Ficheiro contendo todas a funções relativa à estrutura MYUSER.
Definition in file myuser.c.
Function Documentation
MYUSER cloneMYUSER (MYUSER use)
Função que clona um user.
Parameters
user Apontador para o utilizador.
Returns
Clone da estruturao myuser.
Definition at line 186 of file myuser.c.
References myuser::bio, clone_STACKPOST(), createMYUSER(), myuser::id, myuser::posts, myuser::rep, and myuser::username.
{
   MYUSER novo = createMYUSER(0);
   novo->bio = use->bio;
   novo->username = use->username;
   novo->rep = use->rep;
   novo->id = use->id;
   novo->posts = clone_STACKPOST(use->posts);
   return novo;
 }
int compare_user (void * key1, void * key2)
Função que compara 2 keys de user diferentes.
Parameters
key1 Apontador para a primeira key.
key2 Apontador para a segunda key.
Returns
Inteiro a ser usado como booelan.
Definition at line 223 of file myuser.c.
{
     long id1,id2;
     int result;
     id1 = *((long *) key1);
     id2 = *((long *) key2);
     if (id1 == id2)
         result = 0;
     else result = id2 > id1 ? 1 : -1 ;
     return result;
 }
MYUSER createMYUSER (int type)
Função que aloca memória para um user.
Parameters
type Tipo a criar.
Returns
Apontador para a struct myuser.
Definition at line 170 of file myuser.c.
References myuser::bio, initSTACKPOST(), myuser::posts, myuser::type, and myuser::username.
{
     MYUSER conta = malloc(sizeof(struct myuser));
   conta->bio = NULL;
   conta->username = NULL;
   conta->type = type;
   if (type)
     conta->posts = initSTACKPOST(1);
   else conta->posts = NULL;
     return conta;
 }
TREE createMYUSERS_TREE (char * path)
Função lê o ficheiro User.xml e cria uma arvore.
Parameters
path Path para o ficheiro a dar parse.
Returns
Apontador para a arvore criada.
Definition at line 313 of file myuser.c.
References compare_user(), createMYUSER(), createTREE(), freeKey(), freeMYUSER(), myuser::id, insere_tree(), myuser::rep, setBio(), setIdUSER(), setRp(), setUsername(), and xml_file_to_struct().
{
     xmlDocPtr doc;
   xmlNodePtr ptr;
   struct _xmlAttr * cur;
   xmlNodePtr aux;
   MYUSER use = NULL;
   TREE tree = createTREE(&compare_user,&freeKey,&freeMYUSER,NULL);
   if (!(xml_file_to_struct(&doc,&ptr,path)))
     return tree;
     long id = 0;
   long * keyid = NULL;
     int rep;
     aux = ptr->children->next;
     xmlChar *key;
   while (aux != NULL){
     if (strcmp((char*)aux->name,"row")==0){
           use = createMYUSER(1);
       cur = aux->properties;
         while (cur != NULL) {
           key = xmlNodeListGetString(doc,cur->children,1);
             if (strcmp((char*)cur->name,"Id")==0){
                       id = atol((char*)key);
                       setIdUSER(use,id);
                   }
                   if (strcmp((char*)cur->name,"Reputation")==0){
                       rep = atoi((char*)key);
                       setRp(use,rep);
                   }
                   if (strcmp((char*)cur->name,"DisplayName")==0){
                       setUsername(use,(char*)key);
                   }
                   if (strcmp((char*)cur->name,"AboutMe")==0){
             if (key == NULL)
               setBio(use,NULL);
             else setBio(use,(char*)key);
                   }
           xmlFree(key);
           cur = cur->next;
         }
         keyid = malloc(sizeof(long));
         *keyid = id;
         tree = insere_tree(tree,keyid,use);
     }
     aux = aux->next;
   }
   xmlFreeDoc(doc);
   xmlCleanupParser();
   return tree;
 }
void freeKey (void * a)
Função que liberta a memória de um key.
Parameters
a Apontador para a key.
Definition at line 241 of file myuser.c.
                       {
   long * b;
     if (a){
         b = (long *) a;
     free(b);
   }
 }
void freeMYUSER (void * aux)
Função que liberta a memória de um user.
Parameters
aux Memória a libertar.
Definition at line 201 of file myuser.c.
References myuser::bio, freeSTACKPOST_COM_CLONE(), freeSTACKPOST_SEM_CLONE(), myuser::posts, myuser::type, and myuser::username.
{
   MYUSER conta;
     if (aux != NULL){
     conta = (MYUSER) aux;
     if (conta->type == 1){
       if (conta->bio)
             free(conta->bio);
       if (conta->username)
             free(conta->username);
       freeSTACKPOST_SEM_CLONE(conta->posts);
     }
     else freeSTACKPOST_COM_CLONE(conta->posts);
         free(conta);
     }
 }
void freeTreeUSER (TREE tree)
Função que liberta a memória da arvóre alocada.
Parameters
tree Apontador para a estrutura da árvore.
Definition at line 253 of file myuser.c.
References freeTREE_AVL().
{
   freeTREE_AVL(tree);
 }
char* getBiography (MYUSER use)
Função que devolve a biografia do user.
Parameters
use Apontador para o user.
Returns
Biografia do user.
Definition at line 50 of file myuser.c.
References myuser::bio, and mystrdup().
{
   if (use)
     return mystrdup(use->bio);
   return NULL;
 }
long getIdMYUSER (MYUSER use)
Função que devolve o id do user.
Parameters
use Apontador para o user.
Returns
ID do user.
Definition at line 21 of file myuser.c.
References myuser::id.
{
   return use->id;
 }
STACKPOST getMYLISTuser (MYUSER use)
Função que devolve a lista de posts de um USER.
Parameters
use Apontador para o user.
Returns
Lista de posts feito pelo user.
Definition at line 61 of file myuser.c.
References myuser::posts.
{
   if (use) return use->posts;
   return NULL;
 }
long* getNposts (MYUSER use, int n, int * n_elem)
Função que devolve os ultimos N posts de um dado utilizador.
Parameters
use Apontador para o user.
n Número de posts.
n_elem Apontador para onde se colocam o número de valores inseridos.
Returns
Array com os ultimos N posts do user.
Definition at line 73 of file myuser.c.
References get_ele_index_STACKPOST(), get_NUM_eleSTACKPOST(), getIdP(), getPostTypeIdP(), and myuser::posts.
{
   long * r = malloc(n*sizeof(long));
   int i = 0;
   MYPOST post = NULL;
   long k = get_NUM_eleSTACKPOST(use->posts), t = 0;
   for(t=0; i < n && t < k; t++){
     post = get_ele_index_STACKPOST(use->posts,t);
     if (post != NULL && (getPostTypeIdP(post) == 2 || getPostTypeIdP(post) == 1)){
       r[i++] = getIdP(post);
     }
   }
   *n_elem = i;
   return r;
 }
long getNUM_POST_MYUSER (MYUSER use)
Função que devolve o número de posts de um utilizador.
Parameters
use Apontador para o user.
Returns
Numero de posts feitos pelo user.
Definition at line 94 of file myuser.c.
References get_NUM_eleSTACKPOST(), and myuser::posts.
{
   if (use)
     return get_NUM_eleSTACKPOST(use->posts);
   return 0;
 }
int getREPMYUSER (MYUSER use)
Função que devolve a rep do user.
Parameters
use Apontador para o user.
Returns
REP do user.
Definition at line 30 of file myuser.c.
References myuser::rep.
{
   return use->rep;
 }
char* getUsername (MYUSER use)
Função que devolve o Username do user.
Parameters
use Apontador para o user.
Returns
Username do user.
Definition at line 39 of file myuser.c.
References mystrdup(), and myuser::username.
{
   if (use)
     return mystrdup(use->username);
   return NULL;
 }
void print_post_MYUSER (MYUSER use)
Função que imprime os id dos post de um utilizador.
Parameters
use Apontador para o user.
Definition at line 104 of file myuser.c.
References free_MYdate(), get_ele_index_STACKPOST(), get_MYday(), get_MYmonth(), get_MYyear(), get_NUM_eleSTACKPOST(), getDateP(), getIdP(), and myuser::posts.
{
   if (!use){
     printf("error\n");
   }
   MYPOST post = NULL;
   MYDATE data;
   int i = 0;
   long k = get_NUM_eleSTACKPOST(use->posts);
   printf("Ne:%ld\n",k);
   for(i = 0; i < k;i++){
     post = get_ele_index_STACKPOST(use->posts,i);
     if (post != NULL){
       data = getDateP(post);
       if (data != NULL){
         printf("Data-> D:%d M:%d A:%d || ID:%ld \n",get_MYday(data),get_MYmonth(data),get_MYyear(data), getIdP(post));
         free_MYdate(data);
       }
     }
   }
   printf("I=%d\n",i);
 }
MYUSER search_USER (TREE tree, long id)
Função que procura um user na estrutura com clone.
Parameters
tree Estrutura da árvore.
id Id do user a procurar.
Returns
Estrutura clonada apos feita procura, retorna NULL caso a procura falhe.
Definition at line 263 of file myuser.c.
References cloneMYUSER(), and search_AVL().
{
   int valid;
   MYUSER use = search_AVL(tree,&id,&valid);
   if (valid)
     return cloneMYUSER(use);
   return NULL;
 }
static MYUSER search_USER_internal (TREE tree, long id) static
Função que procura um user na estrutura sem clone.
Parameters
tree Estrutura da árvore.
id Id do user a procurar.
Returns
Estrutura sem ser clonada apos feita procura, retorna NULL caso a procura falhe.
Definition at line 278 of file myuser.c.
References search_AVL().
{
   int valid;
   MYUSER use = search_AVL(tree,&id,&valid);
   if (valid)
     return use;
   return NULL;
 }
static void setBio (MYUSER use, char * bio) static
Função que altera a biografia de um user.
Parameters
use Apontador para a struct do user.
bio Biografia a colocar no user.
Definition at line 150 of file myuser.c.
References myuser::bio, and mystrdup().
{
   if (bio)
       use->bio = mystrdup(bio);
   else use->bio = NULL;
 }
static void setIdUSER (MYUSER use, long id) static
Função que altera o Id de um user.
Parameters
use Apontador para a struct do user.
id Id do user a colocar.
Definition at line 132 of file myuser.c.
References myuser::id.
{
     use->id = id;
 }
int setPostToUSER (TREE tree, long id, MYPOST data)
Função mete um post no correspondete user.
Parameters
tree Árvore de users.
id Identificador do user.
data Informação do post.
Returns
Inteiro a ser usado como booelan.
Definition at line 295 of file myuser.c.
References getTYPECLONEP(), insereSTACKPOST(), myuser::posts, and search_USER_internal().
{
   MYUSER use;
   if (!getTYPECLONEP(data))
     return -1;
   use = search_USER_internal(tree,id);
   if (use == NULL)
     return -1;
   insereSTACKPOST(use->posts,data);
   return 1;
 }
static void setRp (MYUSER use, int rep) static
Função que altera a reputação de um user.
Parameters
use Apontador para a struct do user.
rep Reputação do user a colocar.
Definition at line 141 of file myuser.c.
References myuser::rep.
{
     use->rep = rep;
 }
static void setUsername (MYUSER use, char * nome) static
Função que obtém altera o nome de um user.
Parameters
use Apontador para a struct do user.
nome Nome do user a colocar.
Definition at line 161 of file myuser.c.
References mystrdup(), and myuser::username.
{
     use->username = mystrdup(nome);
 }