ProjetoLI3: mytags.h File Reference
mytags.h File Reference
#include "loading.h"
#include <glib.h>
#include <string.h>
#include <common.h>
Functions
void freeHASH_TAGS (GHashTable *table)
Função dá free a uma hashtable.
gboolean hash_equal (const void *data1, const void *data2)
Função que ve se duas keys são iguais.
GHashTable * createMYTAGS_HASH (char *path)
Função que efetua o parsing do ficheiro das Tags e as coloca numa tabela de hash do glib.
Function Documentation
GHashTable* createMYTAGS_HASH (char * path)
Função que efetua o parsing do ficheiro das Tags e as coloca numa tabela de hash do glib.
Parameters
path Path para o ficheiro xml.
Returns
Tabela de HASH das tags.
Definition at line 35 of file mytags.c.
References hash_equal(), mystrdup(), and xml_file_to_struct().
{
   xmlDocPtr doc;
   xmlNodePtr ptr;
   struct _xmlAttr * cur;
   xmlNodePtr aux;
   GHashTable * table = g_hash_table_new_full(&g_str_hash,&hash_equal,&free,&free);
   if (!(xml_file_to_struct(&doc,&ptr,path)))
     return table;
   long id = -2;
   long * keyid = NULL;
   char * tag = NULL;
   aux = ptr->children->next;
     xmlChar *key;
   while (aux) {
     if (strcmp( (char*) aux->name,"row") == 0){
       cur = aux->properties;
       while (cur) {
         key = xmlNodeListGetString(doc,cur->children,1);
         if (strcmp( (char *) cur->name,"Id") == 0)
           id = atol((char*)key);
         if (strcmp( (char *) cur->name,"TagName") == 0){
           tag = mystrdup((char*)key);
         }
         xmlFree(key);
         cur = cur->next;
       }
       if ((id != -2) && tag){
         keyid = malloc(sizeof(long));
         *keyid = id;
         g_hash_table_insert(table,tag,keyid);
       }
       id = -2;
       tag = NULL;
     }
     aux = aux->next;
   }
   xmlFreeDoc(doc);
   xmlCleanupParser();
   return table;
 }
void freeHASH_TAGS (GHashTable * table)
Função dá free a uma hashtable.
Parameters
table Apontador a hashtable.
Definition at line 11 of file mytags.c.
{
   g_hash_table_destroy(table);
 }
gboolean hash_equal (const void * data1, const void * data2)
Função que ve se duas keys são iguais.
Parameters
data1 Apontador para a key1.
data2 Apontador para a key2.
Returns
boolean (TRUE caso encontre FALSE caso nao).
Definition at line 21 of file mytags.c.
{
   char * aux1 = (char *) data1;
   char * aux2 = (char *) data2;
   int x = strcmp(aux1,aux2);
   return x == 0 ? TRUE : FALSE;
 }