ProjetoLI3: mytree.h File Reference
mytree.h File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include "mydate.h"
Macros
#define POSTORDER 1
#define INORDER 2
#define PERORDER 3
Typedefs
typedef struct tree * TREE
Functions
int TREE_balance (TREE tre)
Função verifica se a arvore da estrutura é balanceada.
TREE insere_tree (TREE gl, void *key, void *data)
Função insere um elemento na árvore.
TREE createTREE (void *f_compare, void *destroy_key, void *destroy_data, void *replace)
Função cria a estrutura que contêm a árvore.
void freeTREE_AVL (TREE tre)
Função liberta a memória da estrutura Tree.
void freeTREES_POSTS (TREE postTreeId, TREE postTreeData)
void * search_AVL (TREE tree, void *key, int *valid)
Função que procura um elemento na árvore.
void all_nodes_TREE (TREE e, void(*f_nodo)(void *, void *), void *data1)
Função que vai ser aplicada a todos os nodos.
void all_nodes_With_Condition (TREE tree, void *data1, void *data2, void(*f_nodo)(void *, void *, void *), void *data3, void *data4)
Função que aplica uma função aos nodos que satisfazem uma condição.
int test_TREE_PROP (TREE tree)
Função que testa as propriedas da tree.
long NUM_nodes (TREE t)
Função que devolve o número de nodos da árvore.
void trans_tree (TREE e, void(*f_nodo)(void *, void *, void *, void *), void *data1, void *data2, void *begin, void *end, int travessia, int n)
Função que faz uma travessia na árvore.
Macro Definition Documentation
#define INORDER 2
Definition at line 5 of file mytree.h.
#define PERORDER 3
Definition at line 6 of file mytree.h.
#define POSTORDER 1
Definition at line 4 of file mytree.h.
Typedef Documentation
typedef struct tree* TREE
Definition at line 14 of file mytree.h.
Function Documentation
void all_nodes_TREE (TREE e, void(*)(void *, void *) f_nodo, void * data1)
Função que vai ser aplicada a todos os nodos.
Parameters
e Apontador para a estrutura que contem a AVL.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar à função a aplicar.
Definition at line 437 of file mytree.c.
References all_nodes_trans(), and tree::arv.
{
   if (f_nodo != NULL)
     all_nodes_trans(e->arv,f_nodo,data1);
 }
void all_nodes_With_Condition (TREE tree, void * data1, void * data2, void(*)(void *, void *, void *) f_nodo, void * data3, void * data4)
Função que aplica uma função aos nodos que satisfazem uma condição.
Parameters
tree Apontador para a estrutura que contém a árvore.
data1 Apontador para a data1 a comparar.
data2 Apontador para a data2 a comparar.
f_nodo Função a aplicar em todos os nodos.
data3 Aparametro 1 a passar à função que aplica nos nodos.
data4 Aparametro 2 a passar à função que aplica nos nodos.
Definition at line 478 of file mytree.c.
References all_nodes_With_key_Condition(), tree::arv, and tree::f_compare.
{
   all_nodes_With_key_Condition(tree->arv,data1,data2,tree->f_compare,f_nodo,data3,data4);
 }
TREE createTREE (void * f_compare, void * destroy_key, void * destroy_data, void * replace)
Função cria a estrutura que contêm a árvore.
Parameters
f_compare Apontador para a função de comparação.
destroy_key Apontador para a função que dá free à key.
destroy_data Apontador para a função que dá free à data.
replace Apontador para a função que dá replace à informação.
Returns
Apontador para a estrutura criada.
Definition at line 302 of file mytree.c.
References tree::arv, tree::destroy_data, tree::destroy_key, tree::f_compare, tree::heigth, tree::nnodes, and tree::replace_fun.
{
     TREE a = malloc(sizeof(struct tree));
     a->nnodes = 0;
     a->heigth = 0;
     a->arv = NULL;
   a->replace_fun = replace;
     a->f_compare = f_compare;
   a->destroy_key = destroy_key;
   a->destroy_data = destroy_data;
     return a;
 }
void freeTREE_AVL (TREE tre)
Função liberta a memória da estrutura Tree.
Parameters
tree Apontador para a tree.
Definition at line 341 of file mytree.c.
References tree::arv, tree::destroy_data, tree::destroy_key, and freeAVL().
{
   if(tre){
     freeAVL(tre->arv,tre->destroy_key,tre->destroy_data);
     free(tre);
   }
 }
void freeTREES_POSTS (TREE postTreeId, TREE postTreeData)
TREE insere_tree (TREE gl, void * key, void * data)
Função insere um elemento na árvore.
Parameters
gl Apontador para a estrutura que guarda a árvore.
key Apontador para a key a inserir.
data Apontador para a data a inserir.
Returns
Apontador para a estrutura após ser inserido o valor.
Definition at line 217 of file mytree.c.
References AVBin::altura, tree::arv, balance(), create_new_node(), AVBin::data, tree::destroy_key, AVBin::dir, AVBin::esq, tree::f_compare, implementa_alt(), AVBin::key, MAX_SIZE, tree::nnodes, and tree::replace_fun.
{
     AVL queue[MAX_SIZE];
     AVL a = gl->arv;
   int replace = 0;
   int side;
     int idx = 0;
     queue[idx++] = NULL;
     if (!a){
         a = create_new_node(key,data);
     gl->arv = a;
     }
     else{
         while(1){
       side = (gl->f_compare(a->key,key));
       if (side == 0){
         if (gl->replace_fun != NULL){
           replace = 1;
           a->data=gl->replace_fun(a->data,data);
           if (gl->destroy_key != NULL)
             gl->destroy_key(key);
           break;
         }
       }
             if (side > 0){
                 if (a->dir){
                     queue[idx++] = a;
                     a = a->dir;
                 }
                 else {
                     a->dir = create_new_node(key,data);
                     break;
                 }
             }
             else {
                 if (a->esq){
                     queue[idx++] = a;
                     a = a->esq;
                 }
                 else{
                     a->esq = create_new_node(key,data);
                     break;
                 }
             }
         }
         AVL pai;
         int check_side, balan;
     if (replace == 0){
           while(1){
               pai = queue[--idx];
               check_side = ((!pai) ||pai->esq == a);
               implementa_alt(&a);
               balan = altura(a->dir) - altura(a->esq);
               if (balan < -1 || balan > 1){
                   a = balance(a);
                   if (!pai)
                       break;
                   else if (check_side)
                       pai->esq = a;
                   else pai->dir = a;
               }
               if(!pai)
                   break;
               a = pai;
           }
       gl->arv = a;
     }
     }
   gl->nnodes++;
     return gl;
 }
long NUM_nodes (TREE t)
Função que devolve o número de nodos da árvore.
Parameters
tree Estrutura que contém a árvore.
Returns
Numero de nodos da árvore.
Definition at line 502 of file mytree.c.
References tree::nnodes.
                       {
   return t->nnodes;
 }
void* search_AVL (TREE tree, void * key, int * valid)
Função que procura um elemento na árvore.
Parameters
tree Estrutura que contém a árvore.
key Apontador para a key a procurar.
valid Apontador para o passar o resultado da procura.
Returns
Data da árvore apos ser procurado o elemento, retorna NULL caso falhe na procura.
Definition at line 359 of file mytree.c.
References tree::arv, AVBin::data, AVBin::dir, AVBin::esq, tree::f_compare, and AVBin::key.
{
   AVL node = tree->arv;
   int result = 0;
   while((!result) && node){
     if (tree->f_compare(node->key,key) == 0){
       result = 1;
     }
     else if (tree->f_compare(node->key,key) == 1)
       node = node->dir;
     else node = node ->esq;
   }
   *valid = result;
   if (result)
     return node->data;
   return NULL;
 }
int test_TREE_PROP (TREE tree)
Função que testa as propriedas da tree.
Parameters
tree Estrutura que contém a árvore.
Returns
Inteiro a ser usado como booelan.
Definition at line 488 of file mytree.c.
References tree::arv, check_altura(), isBalanced(), and isSearch().
{
   int alturas,procura,balanceada;
   balanceada = isBalanced(tree->arv);
   alturas = check_altura(tree->arv);
   procura = isSearch(tree->arv,tree);
   return balanceada && alturas && procura;
 }
void trans_tree (TREE e, void(*)(void *, void *, void *, void *) f_nodo, void * data1, void * data2, void * begin, void * end, int travessia, int n)
Função que faz uma travessia na árvore.
Parameters
e Apontador para a arvore.
f_nodo Função a aplicar a cada nodo.
data1 Apontador a passar como argumento à função a aplicar.
data2 Apontador a passar como argumento à função a aplicar.
begin Data início do intervalo a que o nodo tem de pertencer. (nullable)
end Data início do intervalo a que o nodo tem de pertencer. (nullable)
travessia Tipo de travessia.
n Número máximo de nodos a percorrer. (nullable)
Definition at line 694 of file mytree.c.
References tree::arv, trans_4_args(), trans_inorder(), trans_posorder(), trans_preorder(), and trans_revinorder().
{
   if (!e)
     return;
   if (travessia == 1)
     trans_posorder(e->arv,f_nodo,data1, data2, begin, end, &n);
   else if (travessia == 2)
     trans_inorder(e->arv,f_nodo,data1, data2, begin, end, &n);
   else if (travessia == 3)
     trans_preorder(e->arv,f_nodo,data1, data2, begin, end, &n);
   else if (travessia == 4) {
     trans_revinorder(e->arv, f_nodo, data1, data2, begin, end, &n);
   }
   else if (travessia == 5){
     trans_4_args(e->arv, f_nodo, data1, data2, begin, end);
   }
 }
int TREE_balance (TREE tre)
Função verifica se a arvore da estrutura é balanceada.
Parameters
tree Apontador para a estrutura.
Returns
Inteiro a ser usado como boolean.
Definition at line 94 of file mytree.c.
References tree::arv, and isBalanced().
{
   return isBalanced(tre->arv);
 }