ProjetoLI3: pair.c File Reference
pair.c File Reference
#include <stdlib.h>
#include <string.h>
#include <common.h>
#include "pair.h"
Classes
struct str_pair
struct long_pair
Functions
STR_pair create_str_pair (char *fst, char *snd)
void set_fst_str (STR_pair pair, char *str)
void set_snd_str (STR_pair pair, char *str)
char * get_fst_str (STR_pair pair)
char * get_snd_str (STR_pair pair)
void free_str_pair (STR_pair pair)
LONG_pair create_long_pair (long fst, long snd)
void set_fst_long (LONG_pair pair, long l)
void set_snd_long (LONG_pair pair, long l)
long get_fst_long (LONG_pair pair)
long get_snd_long (LONG_pair pair)
void free_long_pair (LONG_pair pair)
Function Documentation
LONG_pair create_long_pair (long fst, long snd)
Definition at line 51 of file pair.c.
References str_pair::fst, long_pair::fst, str_pair::snd, and long_pair::snd.
{
   LONG_pair p = malloc(sizeof(struct long_pair));
   p->fst = fst;
   p->snd = snd;
   return p;
 }
STR_pair create_str_pair (char * fst, char * snd)
Definition at line 12 of file pair.c.
References str_pair::fst, mystrdup(), and str_pair::snd.
{
   STR_pair p = malloc(sizeof(struct str_pair));
   p->fst = mystrdup(fst);
   p->snd = mystrdup(snd);
   return p;
 }
void free_long_pair (LONG_pair pair)
Definition at line 74 of file pair.c.
{
     free(pair);
 }
void free_str_pair (STR_pair pair)
Definition at line 37 of file pair.c.
References str_pair::fst, and str_pair::snd.
{
   if(pair) {
     free(pair->fst);
     free(pair->snd);
     free(pair);
   }
 }
long get_fst_long (LONG_pair pair)
Definition at line 66 of file pair.c.
References long_pair::fst.
{
   return pair->fst;
 }
char* get_fst_str (STR_pair pair)
Definition at line 29 of file pair.c.
References str_pair::fst, and mystrdup().
{
   return pair? mystrdup(pair->fst) : NULL;
 }
long get_snd_long (LONG_pair pair)
Definition at line 70 of file pair.c.
References long_pair::snd.
{
   return pair->snd;
 }
char* get_snd_str (STR_pair pair)
Definition at line 33 of file pair.c.
References mystrdup(), and str_pair::snd.
{
   return pair? mystrdup(pair->snd) : NULL;
 }
void set_fst_long (LONG_pair pair, long l)
Definition at line 58 of file pair.c.
References long_pair::fst.
{
   pair->fst = l;
 }
void set_fst_str (STR_pair pair, char * str)
Definition at line 19 of file pair.c.
References str_pair::fst, and mystrdup().
{
   free(pair->fst);
   pair->fst = mystrdup(str);
 }
void set_snd_long (LONG_pair pair, long l)
Definition at line 62 of file pair.c.
References long_pair::snd.
{
   pair->snd = l;
 }
void set_snd_str (STR_pair pair, char * str)
Definition at line 24 of file pair.c.
References mystrdup(), and str_pair::snd.
{
   free(pair->snd);
   pair->snd = mystrdup(str);
 }